<?php error_reporting(0); ?>   
    <option <?php if($icon == 'fa-500px'){echo 'selected';}?> value='fa-500px'>&#xf26e; fa-500px</option>
        <option data-icon="fa-user" <?php if($icon == 'fa-address-book'){echo 'selected';}?> value='fa-address-book'>&#xf2b9; fa-address-book</option>
        <option <?php if($icon == 'fa-address-book-o'){echo 'selected';}?> value='fa-address-book-o'>&#xf2ba; fa-address-book-o</option>
        <option <?php if($icon == 'fa-address-card'){echo 'selected';}?> value='fa-address-card'>&#xf2bb; fa-address-card</option>
        <option <?php if($icon == 'fa-address-card-o'){echo 'selected';}?> value='fa-address-card-o'>&#xf2bc; fa-address-card-o</option>
        <option <?php if($icon == 'fa-adjust'){echo 'selected';}?> value='fa-adjust'>&#xf042; fa-adjust</option>
        <option <?php if($icon == 'fa-adn'){echo 'selected';}?> value='fa-adn'>&#xf170; fa-adn</option>
        <option <?php if($icon == 'fa-align-center'){echo 'selected';}?> value='fa-align-center'>&#xf037; fa-align-center</option>
        <option <?php if($icon == 'fa-align-justify'){echo 'selected';}?> value='fa-align-justify'>&#xf039; fa-align-justify</option>
        <option <?php if($icon == 'fa-align-left'){echo 'selected';}?> value='fa-align-left'>&#xf036; fa-align-left</option>
        <option <?php if($icon == 'fa-align-right'){echo 'selected';}?> value='fa-align-right'>&#xf038; fa-align-right</option>
        <option <?php if($icon == 'fa-amazon'){echo 'selected';}?> value='fa-amazon'>&#xf270; fa-amazon</option>
        <option <?php if($icon == 'fa-ambulance'){echo 'selected';}?> value='fa-ambulance'>&#xf0f9; fa-ambulance</option>
        <option <?php if($icon == 'fa-american-sign-language-interpreting'){echo 'selected';}?> value='fa-american-sign-language-interpreting'>&#xf2a3; fa-american-sign-language-interpreting</option>
        <option <?php if($icon == 'fa-anchor'){echo 'selected';}?> value='fa-anchor'>&#xf13d; fa-anchor</option>
        <option <?php if($icon == 'fa-android'){echo 'selected';}?> value='fa-android'>&#xf17b; fa-android</option>
                <option <?php if($icon == 'fa-angellist'){echo 'selected';}?> value='fa-angellist'>&#xf209; fa-angellist</option>
        <option <?php if($icon == 'fa-angle-double-down'){echo 'selected';}?> value='fa-angle-double-down'>&#xf103; fa-angle-double-down</option>
        <option <?php if($icon == 'fa-angle-double-left'){echo 'selected';}?> value='fa-angle-double-left'>&#xf100; fa-angle-double-left</option>
        <option <?php if($icon == 'fa-angle-double-right'){echo 'selected';}?> value='fa-angle-double-right'>&#xf101; fa-angle-double-right</option>
        <option <?php if($icon == 'fa-angle-double-up'){echo 'selected';}?> value='fa-angle-double-up'>&#xf102; fa-angle-double-up</option>
        <option <?php if($icon == 'fa-angle-down'){echo 'selected';}?> value='fa-angle-down'>&#xf107; fa-angle-down</option>
        <option <?php if($icon == 'fa-angle-left'){echo 'selected';}?> value='fa-angle-left'>&#xf104; fa-angle-left</option>
        <option <?php if($icon == 'fa-angle-right'){echo 'selected';}?> value='fa-angle-right'>&#xf105; fa-angle-right</option>
        <option <?php if($icon == 'fa-angle-up'){echo 'selected';}?> value='fa-angle-up'>&#xf106; fa-angle-up</option>
        <option <?php if($icon == 'fa-apple'){echo 'selected';}?> value='fa-apple'>&#xf179; fa-apple</option>
        <option <?php if($icon == 'fa-archive'){echo 'selected';}?> value='fa-archive'>&#xf187; fa-archive</option>
        <option <?php if($icon == 'fa-area-chart'){echo 'selected';}?> value='fa-area-chart'>&#xf1fe; fa-area-chart</option>
        <option <?php if($icon == 'fa-arrow-circle-down'){echo 'selected';}?> value='fa-arrow-circle-down'>&#xf0ab; fa-arrow-circle-down</option>
        <option <?php if($icon == 'fa-arrow-circle-left'){echo 'selected';}?> value='fa-arrow-circle-left'>&#xf0a8; fa-arrow-circle-left</option>
        <option <?php if($icon == 'fa-arrow-circle-o-down'){echo 'selected';}?> value='fa-arrow-circle-o-down'>&#xf01a; fa-arrow-circle-o-down</option>
        <option <?php if($icon == 'fa-arrow-circle-o-left'){echo 'selected';}?> value='fa-arrow-circle-o-left'>&#xf190; fa-arrow-circle-o-left</option>
        <option <?php if($icon == 'fa-arrow-circle-o-right'){echo 'selected';}?> value='fa-arrow-circle-o-right'>&#xf18e; fa-arrow-circle-o-right</option>
        <option <?php if($icon == 'fa-arrow-circle-o-up'){echo 'selected';}?> value='fa-arrow-circle-o-up'>&#xf01b; fa-arrow-circle-o-up</option>
        <option <?php if($icon == 'fa-arrow-circle-right'){echo 'selected';}?> value='fa-arrow-circle-right'>&#xf0a9; fa-arrow-circle-right</option>
        <option <?php if($icon == 'fa-arrow-circle-up'){echo 'selected';}?> value='fa-arrow-circle-up'>&#xf0aa; fa-arrow-circle-up</option>
        <option <?php if($icon == 'fa-arrow-down'){echo 'selected';}?> value='fa-arrow-down'>&#xf063; fa-arrow-down</option>
        <option <?php if($icon == 'fa-arrow-left'){echo 'selected';}?> value='fa-arrow-left'>&#xf060; fa-arrow-left</option>
        <option <?php if($icon == 'fa-arrow-right'){echo 'selected';}?> value='fa-arrow-right'>&#xf061; fa-arrow-right</option>
        <option <?php if($icon == 'fa-arrow-up'){echo 'selected';}?> value='fa-arrow-up'>&#xf062; fa-arrow-up</option>
        <option <?php if($icon == 'fa-arrows'){echo 'selected';}?> value='fa-arrows'>&#xf047; fa-arrows</option>
        <option <?php if($icon == 'fa-arrows-alt'){echo 'selected';}?> value='fa-arrows-alt'>&#xf0b2; fa-arrows-alt</option>
        <option <?php if($icon == 'fa-arrows-h'){echo 'selected';}?> value='fa-arrows-h'>&#xf07e; fa-arrows-h</option>
        <option <?php if($icon == 'fa-arrows-v'){echo 'selected';}?> value='fa-arrows-v'>&#xf07d; fa-arrows-v</option>
        <option <?php if($icon == 'fa-asl-interpreting'){echo 'selected';}?> value='fa-asl-interpreting'>&#xf2a3; fa-asl-interpreting</option>
        <option <?php if($icon == 'fa-assistive-listening-systems'){echo 'selected';}?> value='fa-assistive-listening-systems'>&#xf2a2; fa-assistive-listening-systems</option>
        <option <?php if($icon == 'fa-asterisk'){echo 'selected';}?> value='fa-asterisk'>&#xf069; fa-asterisk</option>
        <option <?php if($icon == 'fa-at'){echo 'selected';}?> value='fa-at'>&#xf1fa; fa-at</option>
        <option <?php if($icon == 'fa-audio-description'){echo 'selected';}?> value='fa-audio-description'>&#xf29e; fa-audio-description</option>
        <option <?php if($icon == 'fa-automobile'){echo 'selected';}?> value='fa-automobile'>&#xf1b9; fa-automobile</option>
        <option <?php if($icon == 'fa-backward'){echo 'selected';}?> value='fa-backward'>&#xf04a; fa-backward</option>
        <option <?php if($icon == 'fa-balance-scale'){echo 'selected';}?> value='fa-balance-scale'>&#xf24e; fa-balance-scale</option>
        <option <?php if($icon == 'fa-ban'){echo 'selected';}?> value='fa-ban'>&#xf05e; fa-ban</option>
        <option <?php if($icon == 'fa-bandcamp'){echo 'selected';}?> value='fa-bandcamp'>&#xf2d5; fa-bandcamp</option>
        <option <?php if($icon == 'fa-bank'){echo 'selected';}?> value='fa-bank'>&#xf19c; fa-bank</option>
        <option <?php if($icon == 'fa-bar-chart'){echo 'selected';}?> value='fa-bar-chart'>&#xf080; fa-bar-chart</option>
        <option <?php if($icon == 'fa-bar-chart-o'){echo 'selected';}?> value='fa-bar-chart-o'>&#xf080; fa-bar-chart-o</option>
        <option <?php if($icon == 'fa-barcode'){echo 'selected';}?> value='fa-barcode'>&#xf02a; fa-barcode</option>
        <option <?php if($icon == 'fa-bars'){echo 'selected';}?> value='fa-bars'>&#xf0c9; fa-bars</option>
        <option <?php if($icon == 'fa-bath'){echo 'selected';}?> value='fa-bath'>&#xf2cd; fa-bath</option>
        <option <?php if($icon == 'fa-bathtub'){echo 'selected';}?> value='fa-bathtub'>&#xf2cd; fa-bathtub</option>
        <option <?php if($icon == 'fa-battery'){echo 'selected';}?> value='fa-battery'>&#xf240; fa-battery</option>
        <option <?php if($icon == 'fa-battery-0'){echo 'selected';}?> value='fa-battery-0'>&#xf244; fa-battery-0</option>
        <option <?php if($icon == 'fa-battery-1'){echo 'selected';}?> value='fa-battery-1'>&#xf243; fa-battery-1</option>
        <option <?php if($icon == 'fa-battery-2'){echo 'selected';}?> value='fa-battery-2'>&#xf242; fa-battery-2</option>
        <option <?php if($icon == 'fa-battery-3'){echo 'selected';}?> value='fa-battery-3'>&#xf241; fa-battery-3</option>
        <option <?php if($icon == 'fa-battery-4'){echo 'selected';}?> value='fa-battery-4'>&#xf240; fa-battery-4</option>
        <option <?php if($icon == 'fa-battery-empty'){echo 'selected';}?> value='fa-battery-empty'>&#xf244; fa-battery-empty</option>
        <option <?php if($icon == 'fa-battery-full'){echo 'selected';}?> value='fa-battery-full'>&#xf240; fa-battery-full</option>
        <option <?php if($icon == 'fa-battery-half'){echo 'selected';}?> value='fa-battery-half'>&#xf242; fa-battery-half</option>
        <option <?php if($icon == 'fa-battery-quarter'){echo 'selected';}?> value='fa-battery-quarter'>&#xf243; fa-battery-quarter</option>
                <option <?php if($icon == 'fa-battery-three-quarters'){echo 'selected';}?> value='fa-battery-three-quarters'>&#xf241; fa-battery-three-quarters</option>
        <option <?php if($icon == 'fa-bed'){echo 'selected';}?> value='fa-bed'>&#xf236; fa-bed</option>
        <option <?php if($icon == 'fa-beer'){echo 'selected';}?> value='fa-beer'>&#xf0fc; fa-beer</option>
        <option <?php if($icon == 'fa-behance'){echo 'selected';}?> value='fa-behance'>&#xf1b4; fa-behance</option>
        <option <?php if($icon == 'fa-behance-square'){echo 'selected';}?> value='fa-behance-square'>&#xf1b5; fa-behance-square</option>
        <option <?php if($icon == 'fa-bell'){echo 'selected';}?> value='fa-bell'>&#xf0f3; fa-bell</option>
        <option <?php if($icon == 'fa-bell-o'){echo 'selected';}?> value='fa-bell-o'>&#xf0a2; fa-bell-o</option>
        <option <?php if($icon == 'fa-bell-slash'){echo 'selected';}?> value='fa-bell-slash'>&#xf1f6; fa-bell-slash</option>
        <option <?php if($icon == 'fa-bell-slash-o'){echo 'selected';}?> value='fa-bell-slash-o'>&#xf1f7; fa-bell-slash-o</option>
        <option <?php if($icon == 'fa-bicycle'){echo 'selected';}?> value='fa-bicycle'>&#xf206; fa-bicycle</option>
        <option <?php if($icon == 'fa-binoculars'){echo 'selected';}?> value='fa-binoculars'>&#xf1e5; fa-binoculars</option>
        <option <?php if($icon == 'fa-birthday-cake'){echo 'selected';}?> value='fa-birthday-cake'>&#xf1fd; fa-birthday-cake</option>
        <option <?php if($icon == 'fa-bitbucket'){echo 'selected';}?> value='fa-bitbucket'>&#xf171; fa-bitbucket</option>
        <option <?php if($icon == 'fa-bitbucket-square'){echo 'selected';}?> value='fa-bitbucket-square'>&#xf172; fa-bitbucket-square</option>
        <option <?php if($icon == 'fa-bitcoin'){echo 'selected';}?> value='fa-bitcoin'>&#xf15a; fa-bitcoin</option>
        <option <?php if($icon == 'fa-black-tie'){echo 'selected';}?> value='fa-black-tie'>&#xf27e; fa-black-tie</option>
        <option <?php if($icon == 'fa-blind'){echo 'selected';}?> value='fa-blind'>&#xf29d; fa-blind</option>
        <option <?php if($icon == 'fa-bluetooth'){echo 'selected';}?> value='fa-bluetooth'>&#xf293; fa-bluetooth</option>
        <option <?php if($icon == 'fa-bluetooth-b'){echo 'selected';}?> value='fa-bluetooth-b'>&#xf294; fa-bluetooth-b</option>
        <option <?php if($icon == 'fa-bold'){echo 'selected';}?> value='fa-bold'>&#xf032; fa-bold</option>
        <option <?php if($icon == 'fa-bolt'){echo 'selected';}?> value='fa-bolt'>&#xf0e7; fa-bolt</option>
        <option <?php if($icon == 'fa-bomb'){echo 'selected';}?> value='fa-bomb'>&#xf1e2; fa-bomb</option>
        <option <?php if($icon == 'fa-book'){echo 'selected';}?> value='fa-book'>&#xf02d; fa-book</option>
        <option <?php if($icon == 'fa-bookmark'){echo 'selected';}?> value='fa-bookmark'>&#xf02e; fa-bookmark</option>
        <option <?php if($icon == 'fa-bookmark-o'){echo 'selected';}?> value='fa-bookmark-o'>&#xf097; fa-bookmark-o</option>
        <option <?php if($icon == 'fa-braille'){echo 'selected';}?> value='fa-braille'>&#xf2a1; fa-braille</option>
        <option <?php if($icon == 'fa-briefcase'){echo 'selected';}?> value='fa-briefcase'>&#xf0b1; fa-briefcase</option>
        <option <?php if($icon == 'fa-btc'){echo 'selected';}?> value='fa-btc'>&#xf15a; fa-btc</option>
        <option <?php if($icon == 'fa-bug'){echo 'selected';}?> value='fa-bug'>&#xf188; fa-bug</option>
        <option <?php if($icon == 'fa-building'){echo 'selected';}?> value='fa-building'>&#xf1ad; fa-building</option>
        <option <?php if($icon == 'fa-building-o'){echo 'selected';}?> value='fa-building-o'>&#xf0f7; fa-building-o</option>
        <option <?php if($icon == 'fa-bullhorn'){echo 'selected';}?> value='fa-bullhorn'>&#xf0a1; fa-bullhorn</option>
        <option <?php if($icon == 'fa-bullseye'){echo 'selected';}?> value='fa-bullseye'>&#xf140; fa-bullseye</option>
        <option <?php if($icon == 'fa-bus'){echo 'selected';}?> value='fa-bus'>&#xf207; fa-bus</option>
        <option <?php if($icon == 'fa-buysellads'){echo 'selected';}?> value='fa-buysellads'>&#xf20d; fa-buysellads</option>
        <option <?php if($icon == 'fa-cab'){echo 'selected';}?> value='fa-cab'>&#xf1ba; fa-cab</option>
        <option <?php if($icon == 'fa-calculator'){echo 'selected';}?> value='fa-calculator'>&#xf1ec; fa-calculator</option>
        <option <?php if($icon == 'fa-calendar'){echo 'selected';}?> value='fa-calendar'>&#xf073; fa-calendar</option>
        <option <?php if($icon == 'fa-calendar-check-o'){echo 'selected';}?> value='fa-calendar-check-o'>&#xf274; fa-calendar-check-o</option>
        <option <?php if($icon == 'fa-calendar-minus-o'){echo 'selected';}?> value='fa-calendar-minus-o'>&#xf272; fa-calendar-minus-o</option>
        <option <?php if($icon == 'fa-calendar-o'){echo 'selected';}?> value='fa-calendar-o'>&#xf133; fa-calendar-o</option>
        <option <?php if($icon == 'fa-calendar-plus-o'){echo 'selected';}?> value='fa-calendar-plus-o'>&#xf271; fa-calendar-plus-o</option>
        <option <?php if($icon == 'fa-calendar-times-o'){echo 'selected';}?> value='fa-calendar-times-o'>&#xf273; fa-calendar-times-o</option>
        <option <?php if($icon == 'fa-camera'){echo 'selected';}?> value='fa-camera'>&#xf030; fa-camera</option>
        <option <?php if($icon == 'fa-camera-retro'){echo 'selected';}?> value='fa-camera-retro'>&#xf083; fa-camera-retro</option>
        <option <?php if($icon == 'fa-car'){echo 'selected';}?> value='fa-car'>&#xf1b9; fa-car</option>
        <option <?php if($icon == 'fa-caret-down'){echo 'selected';}?> value='fa-caret-down'>&#xf0d7; fa-caret-down</option>
        <option <?php if($icon == 'fa-caret-left'){echo 'selected';}?> value='fa-caret-left'>&#xf0d9; fa-caret-left</option>
        <option <?php if($icon == 'fa-caret-right'){echo 'selected';}?> value='fa-caret-right'>&#xf0da; fa-caret-right</option>
        <option <?php if($icon == 'fa-caret-square-o-down'){echo 'selected';}?> value='fa-caret-square-o-down'>&#xf150; fa-caret-square-o-down</option>
        <option <?php if($icon == 'fa-caret-square-o-left'){echo 'selected';}?> value='fa-caret-square-o-left'>&#xf191; fa-caret-square-o-left</option>
        <option <?php if($icon == 'fa-caret-square-o-right'){echo 'selected';}?> value='fa-caret-square-o-right'>&#xf152; fa-caret-square-o-right</option>
        <option <?php if($icon == 'fa-caret-square-o-up'){echo 'selected';}?> value='fa-caret-square-o-up'>&#xf151; fa-caret-square-o-up</option>
        <option <?php if($icon == 'fa-caret-up'){echo 'selected';}?> value='fa-caret-up'>&#xf0d8; fa-caret-up</option>
        <option <?php if($icon == 'fa-cart-arrow-down'){echo 'selected';}?> value='fa-cart-arrow-down'>&#xf218; fa-cart-arrow-down</option>
        <option <?php if($icon == 'fa-cart-plus'){echo 'selected';}?> value='fa-cart-plus'>&#xf217; fa-cart-plus</option>
        <option <?php if($icon == 'fa-cc'){echo 'selected';}?> value='fa-cc'>&#xf20a; fa-cc</option>
        <option <?php if($icon == 'fa-cc-amex'){echo 'selected';}?> value='fa-cc-amex'>&#xf1f3; fa-cc-amex</option>
        <option <?php if($icon == 'fa-cc-diners-club'){echo 'selected';}?> value='fa-cc-diners-club'>&#xf24c; fa-cc-diners-club</option>
        <option <?php if($icon == 'fa-cc-discover'){echo 'selected';}?> value='fa-cc-discover'>&#xf1f2; fa-cc-discover</option>
        <option <?php if($icon == 'fa-cc-jcb'){echo 'selected';}?> value='fa-cc-jcb'>&#xf24b; fa-cc-jcb</option>
        <option <?php if($icon == 'fa-cc-mastercard'){echo 'selected';}?> value='fa-cc-mastercard'>&#xf1f1; fa-cc-mastercard</option>
        <option <?php if($icon == 'fa-cc-paypal'){echo 'selected';}?> value='fa-cc-paypal'>&#xf1f4; fa-cc-paypal</option>
        <option <?php if($icon == 'fa-cc-stripe'){echo 'selected';}?> value='fa-cc-stripe'>&#xf1f5; fa-cc-stripe</option>
        <option <?php if($icon == 'fa-cc-visa'){echo 'selected';}?> value='fa-cc-visa'>&#xf1f0; fa-cc-visa</option>
        <option <?php if($icon == 'fa-certificate'){echo 'selected';}?> value='fa-certificate'>&#xf0a3; fa-certificate</option>
        <option <?php if($icon == 'fa-chain'){echo 'selected';}?> value='fa-chain'>&#xf0c1; fa-chain</option>
        <option <?php if($icon == 'fa-chain-broken'){echo 'selected';}?> value='fa-chain-broken'>&#xf127; fa-chain-broken</option>
        <option <?php if($icon == 'fa-check'){echo 'selected';}?> value='fa-check'>&#xf00c; fa-check</option>
        <option <?php if($icon == 'fa-check-circle'){echo 'selected';}?> value='fa-check-circle'>&#xf058; fa-check-circle</option>
        <option <?php if($icon == 'fa-check-circle-o'){echo 'selected';}?> value='fa-check-circle-o'>&#xf05d; fa-check-circle-o</option>
        <option <?php if($icon == 'fa-check-square'){echo 'selected';}?> value='fa-check-square'>&#xf14a; fa-check-square</option>
        <option <?php if($icon == 'fa-check-square-o'){echo 'selected';}?> value='fa-check-square-o'>&#xf046; fa-check-square-o</option>
        <option <?php if($icon == 'fa-chevron-circle-down'){echo 'selected';}?> value='fa-chevron-circle-down'>&#xf13a; fa-chevron-circle-down</option>
        <option <?php if($icon == 'fa-chevron-circle-left'){echo 'selected';}?> value='fa-chevron-circle-left'>&#xf137; fa-chevron-circle-left</option>
        <option <?php if($icon == 'fa-chevron-circle-right'){echo 'selected';}?> value='fa-chevron-circle-right'>&#xf138; fa-chevron-circle-right</option>
        <option <?php if($icon == 'fa-chevron-circle-up'){echo 'selected';}?> value='fa-chevron-circle-up'>&#xf139; fa-chevron-circle-up</option>
        <option <?php if($icon == 'fa-chevron-down'){echo 'selected';}?> value='fa-chevron-down'>&#xf078; fa-chevron-down</option>
        <option <?php if($icon == 'fa-chevron-left'){echo 'selected';}?> value='fa-chevron-left'>&#xf053; fa-chevron-left</option>
        <option <?php if($icon == 'fa-chevron-right'){echo 'selected';}?> value='fa-chevron-right'>&#xf054; fa-chevron-right</option>
        <option <?php if($icon == 'fa-chevron-up'){echo 'selected';}?> value='fa-chevron-up'>&#xf077; fa-chevron-up</option>
        <option <?php if($icon == 'fa-child'){echo 'selected';}?> value='fa-child'>&#xf1ae; fa-child</option>
        <option <?php if($icon == 'fa-chrome'){echo 'selected';}?> value='fa-chrome'>&#xf268; fa-chrome</option>
        <option <?php if($icon == 'fa-circle'){echo 'selected';}?> value='fa-circle'>&#xf111; fa-circle</option>
        <option <?php if($icon == 'fa-circle-o'){echo 'selected';}?> value='fa-circle-o'>&#xf10c; fa-circle-o</option>
        <option <?php if($icon == 'fa-circle-o-notch'){echo 'selected';}?> value='fa-circle-o-notch'>&#xf1ce; fa-circle-o-notch</option>
        <option <?php if($icon == 'fa-circle-thin'){echo 'selected';}?> value='fa-circle-thin'>&#xf1db; fa-circle-thin</option>
        <option <?php if($icon == 'fa-clipboard'){echo 'selected';}?> value='fa-clipboard'>&#xf0ea; fa-clipboard</option>
        <option <?php if($icon == 'fa-clock-o'){echo 'selected';}?> value='fa-clock-o'>&#xf017; fa-clock-o</option>
        <option <?php if($icon == 'fa-clone'){echo 'selected';}?> value='fa-clone'>&#xf24d; fa-clone</option>
        <option <?php if($icon == 'fa-close'){echo 'selected';}?> value='fa-close'>&#xf00d; fa-close</option>
        <option <?php if($icon == 'fa-cloud'){echo 'selected';}?> value='fa-cloud'>&#xf0c2; fa-cloud</option>
        <option <?php if($icon == 'fa-cloud-download'){echo 'selected';}?> value='fa-cloud-download'>&#xf0ed; fa-cloud-download</option>
        <option <?php if($icon == 'fa-cloud-upload'){echo 'selected';}?> value='fa-cloud-upload'>&#xf0ee; fa-cloud-upload</option>
        <option <?php if($icon == 'fa-cny'){echo 'selected';}?> value='fa-cny'>&#xf157; fa-cny</option>
        <option <?php if($icon == 'fa-code'){echo 'selected';}?> value='fa-code'>&#xf121; fa-code</option>
        <option <?php if($icon == 'fa-code-fork'){echo 'selected';}?> value='fa-code-fork'>&#xf126; fa-code-fork</option>
        <option <?php if($icon == 'fa-codepen'){echo 'selected';}?> value='fa-codepen'>&#xf1cb; fa-codepen</option>
        <option <?php if($icon == 'fa-codiepie'){echo 'selected';}?> value='fa-codiepie'>&#xf284; fa-codiepie</option>
        <option <?php if($icon == 'fa-coffee'){echo 'selected';}?> value='fa-coffee'>&#xf0f4; fa-coffee</option>
        <option <?php if($icon == 'fa-cog'){echo 'selected';}?> value='fa-cog'>&#xf013; fa-cog</option>
        <option <?php if($icon == 'fa-cogs'){echo 'selected';}?> value='fa-cogs'>&#xf085; fa-cogs</option>
        <option <?php if($icon == 'fa-columns'){echo 'selected';}?> value='fa-columns'>&#xf0db; fa-columns</option>
        <option <?php if($icon == 'fa-comment'){echo 'selected';}?> value='fa-comment'>&#xf075; fa-comment</option>
        <option <?php if($icon == 'fa-comment-o'){echo 'selected';}?> value='fa-comment-o'>&#xf0e5; fa-comment-o</option>
        <option <?php if($icon == 'fa-commenting'){echo 'selected';}?> value='fa-commenting'>&#xf27a; fa-commenting</option>
        <option <?php if($icon == 'fa-commenting-o'){echo 'selected';}?> value='fa-commenting-o'>&#xf27b; fa-commenting-o</option>
        <option <?php if($icon == 'fa-comments'){echo 'selected';}?> value='fa-comments'>&#xf086; fa-comments</option>
        <option <?php if($icon == 'fa-comments-o'){echo 'selected';}?> value='fa-comments-o'>&#xf0e6; fa-comments-o</option>
        <option <?php if($icon == 'fa-compass'){echo 'selected';}?> value='fa-compass'>&#xf14e; fa-compass</option>
        <option <?php if($icon == 'fa-compress'){echo 'selected';}?> value='fa-compress'>&#xf066; fa-compress</option>
        <option <?php if($icon == 'fa-connectdevelop'){echo 'selected';}?> value='fa-connectdevelop'>&#xf20e; fa-connectdevelop</option>
        <option <?php if($icon == 'fa-contao'){echo 'selected';}?> value='fa-contao'>&#xf26d; fa-contao</option>
        <option <?php if($icon == 'fa-copy'){echo 'selected';}?> value='fa-copy'>&#xf0c5; fa-copy</option>
        <option <?php if($icon == 'fa-copyright'){echo 'selected';}?> value='fa-copyright'>&#xf1f9; fa-copyright</option>
        <option <?php if($icon == 'fa-creative-commons'){echo 'selected';}?> value='fa-creative-commons'>&#xf25e; fa-creative-commons</option>
        <option <?php if($icon == 'fa-credit-card'){echo 'selected';}?> value='fa-credit-card'>&#xf09d; fa-credit-card</option>
        <option <?php if($icon == 'fa-credit-card-alt'){echo 'selected';}?> value='fa-credit-card-alt'>&#xf283; fa-credit-card-alt</option>
        <option <?php if($icon == 'fa-crop'){echo 'selected';}?> value='fa-crop'>&#xf125; fa-crop</option>
        <option <?php if($icon == 'fa-crosshairs'){echo 'selected';}?> value='fa-crosshairs'>&#xf05b; fa-crosshairs</option>
        <option <?php if($icon == 'fa-css3'){echo 'selected';}?> value='fa-css3'>&#xf13c; fa-css3</option>
        <option <?php if($icon == 'fa-cube'){echo 'selected';}?> value='fa-cube'>&#xf1b2; fa-cube</option>
        <option <?php if($icon == 'fa-cubes'){echo 'selected';}?> value='fa-cubes'>&#xf1b3; fa-cubes</option>
        <option <?php if($icon == 'fa-cut'){echo 'selected';}?> value='fa-cut'>&#xf0c4; fa-cut</option>
        <option <?php if($icon == 'fa-cutlery'){echo 'selected';}?> value='fa-cutlery'>&#xf0f5; fa-cutlery</option>
        <option <?php if($icon == 'fa-dashboard'){echo 'selected';}?> value='fa-dashboard'>&#xf0e4; fa-dashboard</option>
        <option <?php if($icon == 'fa-dashcube'){echo 'selected';}?> value='fa-dashcube'>&#xf210; fa-dashcube</option>
        <option <?php if($icon == 'fa-database'){echo 'selected';}?> value='fa-database'>&#xf1c0; fa-database</option>
        <option <?php if($icon == 'fa-deaf'){echo 'selected';}?> value='fa-deaf'>&#xf2a4; fa-deaf</option>
        <option <?php if($icon == 'fa-deafness'){echo 'selected';}?> value='fa-deafness'>&#xf2a4; fa-deafness</option>
        <option <?php if($icon == 'fa-dedent'){echo 'selected';}?> value='fa-dedent'>&#xf03b; fa-dedent</option>
        <option <?php if($icon == 'fa-delicious'){echo 'selected';}?> value='fa-delicious'>&#xf1a5; fa-delicious</option>
        <option <?php if($icon == 'fa-desktop'){echo 'selected';}?> value='fa-desktop'>&#xf108; fa-desktop</option>
        <option <?php if($icon == 'fa-deviantart'){echo 'selected';}?> value='fa-deviantart'>&#xf1bd; fa-deviantart</option>
        <option <?php if($icon == 'fa-diamond'){echo 'selected';}?> value='fa-diamond'>&#xf219; fa-diamond</option>
        <option <?php if($icon == 'fa-digg'){echo 'selected';}?> value='fa-digg'>&#xf1a6; fa-digg</option>
        <option <?php if($icon == 'fa-dollar'){echo 'selected';}?> value='fa-dollar'>&#xf155; fa-dollar</option>
        <option <?php if($icon == 'fa-dot-circle-o'){echo 'selected';}?> value='fa-dot-circle-o'>&#xf192; fa-dot-circle-o</option>
        <option <?php if($icon == 'fa-download'){echo 'selected';}?> value='fa-download'>&#xf019; fa-download</option>
        <option <?php if($icon == 'fa-dribbble'){echo 'selected';}?> value='fa-dribbble'>&#xf17d; fa-dribbble</option>
        <option <?php if($icon == 'fa-drivers-license'){echo 'selected';}?> value='fa-drivers-license'>&#xf2c2; fa-drivers-license</option>
        <option <?php if($icon == 'fa-drivers-license-o'){echo 'selected';}?> value='fa-drivers-license-o'>&#xf2c3; fa-drivers-license-o</option>
        <option <?php if($icon == 'fa-dropbox'){echo 'selected';}?> value='fa-dropbox'>&#xf16b; fa-dropbox</option>
        <option <?php if($icon == 'fa-drupal'){echo 'selected';}?> value='fa-drupal'>&#xf1a9; fa-drupal</option>
        <option <?php if($icon == 'fa-edge'){echo 'selected';}?> value='fa-edge'>&#xf282; fa-edge</option>
        <option <?php if($icon == 'fa-edit'){echo 'selected';}?> value='fa-edit'>&#xf044; fa-edit</option>
        <option <?php if($icon == 'fa-eercast'){echo 'selected';}?> value='fa-eercast'>&#xf2da; fa-eercast</option>
        <option <?php if($icon == 'fa-eject'){echo 'selected';}?> value='fa-eject'>&#xf052; fa-eject</option>
        <option <?php if($icon == 'fa-ellipsis-h'){echo 'selected';}?> value='fa-ellipsis-h'>&#xf141; fa-ellipsis-h</option>
        <option <?php if($icon == 'fa-ellipsis-v'){echo 'selected';}?> value='fa-ellipsis-v'>&#xf142; fa-ellipsis-v</option>
        <option <?php if($icon == 'fa-empire'){echo 'selected';}?> value='fa-empire'>&#xf1d1; fa-empire</option>
        <option <?php if($icon == 'fa-envelope'){echo 'selected';}?> value='fa-envelope'>&#xf0e0; fa-envelope</option>
        <option <?php if($icon == 'fa-envelope-o'){echo 'selected';}?> value='fa-envelope-o'>&#xf003; fa-envelope-o</option>
        <option <?php if($icon == 'fa-envelope-open'){echo 'selected';}?> value='fa-envelope-open'>&#xf2b6; fa-envelope-open</option>
        <option <?php if($icon == 'fa-envelope-open-o'){echo 'selected';}?> value='fa-envelope-open-o'>&#xf2b7; fa-envelope-open-o</option>
        <option <?php if($icon == 'fa-envelope-square'){echo 'selected';}?> value='fa-envelope-square'>&#xf199; fa-envelope-square</option>
        <option <?php if($icon == 'fa-envira'){echo 'selected';}?> value='fa-envira'>&#xf299; fa-envira</option>
        <option <?php if($icon == 'fa-eraser'){echo 'selected';}?> value='fa-eraser'>&#xf12d; fa-eraser</option>
        <option <?php if($icon == 'fa-etsy'){echo 'selected';}?> value='fa-etsy'>&#xf2d7; fa-etsy</option>
        <option <?php if($icon == 'fa-eur'){echo 'selected';}?> value='fa-eur'>&#xf153; fa-eur</option>
        <option <?php if($icon == 'fa-euro'){echo 'selected';}?> value='fa-euro'>&#xf153; fa-euro</option>
        <option <?php if($icon == 'fa-exchange'){echo 'selected';}?> value='fa-exchange'>&#xf0ec; fa-exchange</option>
        <option <?php if($icon == 'fa-exclamation'){echo 'selected';}?> value='fa-exclamation'>&#xf12a; fa-exclamation</option>
        <option <?php if($icon == 'fa-exclamation-circle'){echo 'selected';}?> value='fa-exclamation-circle'>&#xf06a; fa-exclamation-circle</option>
        <option <?php if($icon == 'fa-exclamation-triangle'){echo 'selected';}?> value='fa-exclamation-triangle'>&#xf071; fa-exclamation-triangle</option>
        <option <?php if($icon == 'fa-expand'){echo 'selected';}?> value='fa-expand'>&#xf065; fa-expand</option>
        <option <?php if($icon == 'fa-expeditedssl'){echo 'selected';}?> value='fa-expeditedssl'>&#xf23e; fa-expeditedssl</option>
        <option <?php if($icon == 'fa-external-link'){echo 'selected';}?> value='fa-external-link'>&#xf08e; fa-external-link</option>
        <option <?php if($icon == 'fa-external-link-square'){echo 'selected';}?> value='fa-external-link-square'>&#xf14c; fa-external-link-square</option>
        <option <?php if($icon == 'fa-eye'){echo 'selected';}?> value='fa-eye'>&#xf06e; fa-eye</option>
        <option <?php if($icon == 'fa-eye-slash'){echo 'selected';}?> value='fa-eye-slash'>&#xf070; fa-eye-slash</option>
        <option <?php if($icon == 'fa-eyedropper'){echo 'selected';}?> value='fa-eyedropper'>&#xf1fb; fa-eyedropper</option>
        <option <?php if($icon == 'fa-fa'){echo 'selected';}?> value='fa-fa'>&#xf2b4; fa-fa</option>
        <option <?php if($icon == 'fa-facebook'){echo 'selected';}?> value='fa-facebook'>&#xf09a; fa-facebook</option>
        <option <?php if($icon == 'fa-facebook-f'){echo 'selected';}?> value='fa-facebook-f'>&#xf09a; fa-facebook-f</option>
        <option <?php if($icon == 'fa-facebook-official'){echo 'selected';}?> value='fa-facebook-official'>&#xf230; fa-facebook-official</option>
        <option <?php if($icon == 'fa-facebook-square'){echo 'selected';}?> value='fa-facebook-square'>&#xf082; fa-facebook-square</option>
        <option <?php if($icon == 'fa-fast-backward'){echo 'selected';}?> value='fa-fast-backward'>&#xf049; fa-fast-backward</option>
        <option <?php if($icon == 'fa-fast-forward'){echo 'selected';}?> value='fa-fast-forward'>&#xf050; fa-fast-forward</option>
        <option <?php if($icon == 'fa-fax'){echo 'selected';}?> value='fa-fax'>&#xf1ac; fa-fax</option>
        <option <?php if($icon == 'fa-feed'){echo 'selected';}?> value='fa-feed'>&#xf09e; fa-feed</option>
        <option <?php if($icon == 'fa-female'){echo 'selected';}?> value='fa-female'>&#xf182; fa-female</option>
        <option <?php if($icon == 'fa-fighter-jet'){echo 'selected';}?> value='fa-fighter-jet'>&#xf0fb; fa-fighter-jet</option>
        <option <?php if($icon == 'fa-file'){echo 'selected';}?> value='fa-file'>&#xf15b; fa-file</option>
        <option <?php if($icon == 'fa-file-archive-o'){echo 'selected';}?> value='fa-file-archive-o'>&#xf1c6; fa-file-archive-o</option>
        <option <?php if($icon == 'fa-file-audio-o'){echo 'selected';}?> value='fa-file-audio-o'>&#xf1c7; fa-file-audio-o</option>
        <option <?php if($icon == 'fa-file-code-o'){echo 'selected';}?> value='fa-file-code-o'>&#xf1c9; fa-file-code-o</option>
        <option <?php if($icon == 'fa-file-excel-o'){echo 'selected';}?> value='fa-file-excel-o'>&#xf1c3; fa-file-excel-o</option>
        <option <?php if($icon == 'fa-file-image-o'){echo 'selected';}?> value='fa-file-image-o'>&#xf1c5; fa-file-image-o</option>
        <option <?php if($icon == 'fa-file-movie-o'){echo 'selected';}?> value='fa-file-movie-o'>&#xf1c8; fa-file-movie-o</option>
        <option <?php if($icon == 'fa-file-o'){echo 'selected';}?> value='fa-file-o'>&#xf016; fa-file-o</option>
        <option <?php if($icon == 'fa-file-pdf-o'){echo 'selected';}?> value='fa-file-pdf-o'>&#xf1c1; fa-file-pdf-o</option>
        <option <?php if($icon == 'fa-file-photo-o'){echo 'selected';}?> value='fa-file-photo-o'>&#xf1c5; fa-file-photo-o</option>
        <option <?php if($icon == 'fa-file-picture-o'){echo 'selected';}?> value='fa-file-picture-o'>&#xf1c5; fa-file-picture-o</option>
        <option <?php if($icon == 'fa-file-powerpoint-o'){echo 'selected';}?> value='fa-file-powerpoint-o'>&#xf1c4; fa-file-powerpoint-o</option>
        <option <?php if($icon == 'fa-file-sound-o'){echo 'selected';}?> value='fa-file-sound-o'>&#xf1c7; fa-file-sound-o</option>
        <option <?php if($icon == 'fa-file-text'){echo 'selected';}?> value='fa-file-text'>&#xf15c; fa-file-text</option>
        <option <?php if($icon == 'fa-file-text-o'){echo 'selected';}?> value='fa-file-text-o'>&#xf0f6; fa-file-text-o</option>
        <option <?php if($icon == 'fa-file-video-o'){echo 'selected';}?> value='fa-file-video-o'>&#xf1c8; fa-file-video-o</option>
        <option <?php if($icon == 'fa-file-word-o'){echo 'selected';}?> value='fa-file-word-o'>&#xf1c2; fa-file-word-o</option>
        <option <?php if($icon == 'fa-file-zip-o'){echo 'selected';}?> value='fa-file-zip-o'>&#xf1c6; fa-file-zip-o</option>
        <option <?php if($icon == 'fa-files-o'){echo 'selected';}?> value='fa-files-o'>&#xf0c5; fa-files-o</option>
        <option <?php if($icon == 'fa-film'){echo 'selected';}?> value='fa-film'>&#xf008; fa-film</option>
        <option <?php if($icon == 'fa-filter'){echo 'selected';}?> value='fa-filter'>&#xf0b0; fa-filter</option>
        <option <?php if($icon == 'fa-fire'){echo 'selected';}?> value='fa-fire'>&#xf06d; fa-fire</option>
        <option <?php if($icon == 'fa-fire-extinguisher'){echo 'selected';}?> value='fa-fire-extinguisher'>&#xf134; fa-fire-extinguisher</option>
        <option <?php if($icon == 'fa-firefox'){echo 'selected';}?> value='fa-firefox'>&#xf269; fa-firefox</option>
        <option <?php if($icon == 'fa-first-order'){echo 'selected';}?> value='fa-first-order'>&#xf2b0; fa-first-order</option>
        <option <?php if($icon == 'fa-flag'){echo 'selected';}?> value='fa-flag'>&#xf024; fa-flag</option>
        <option <?php if($icon == 'fa-flag-checkered'){echo 'selected';}?> value='fa-flag-checkered'>&#xf11e; fa-flag-checkered</option>
        <option <?php if($icon == 'fa-flag-o'){echo 'selected';}?> value='fa-flag-o'>&#xf11d; fa-flag-o</option>
        <option <?php if($icon == 'fa-flash'){echo 'selected';}?> value='fa-flash'>&#xf0e7; fa-flash</option>
        <option <?php if($icon == 'fa-flask'){echo 'selected';}?> value='fa-flask'>&#xf0c3; fa-flask</option>
        <option <?php if($icon == 'fa-flickr'){echo 'selected';}?> value='fa-flickr'>&#xf16e; fa-flickr</option>
        <option <?php if($icon == 'fa-floppy-o'){echo 'selected';}?> value='fa-floppy-o'>&#xf0c7; fa-floppy-o</option>
        <option <?php if($icon == 'fa-folder'){echo 'selected';}?> value='fa-folder'>&#xf07b; fa-folder</option>
        <option <?php if($icon == 'fa-folder-o'){echo 'selected';}?> value='fa-folder-o'>&#xf114; fa-folder-o</option>
        <option <?php if($icon == 'fa-folder-open'){echo 'selected';}?> value='fa-folder-open'>&#xf07c; fa-folder-open</option>
        <option <?php if($icon == 'fa-folder-open-o'){echo 'selected';}?> value='fa-folder-open-o'>&#xf115; fa-folder-open-o</option>
        <option <?php if($icon == 'fa-font'){echo 'selected';}?> value='fa-font'>&#xf031; fa-font</option>
        <option <?php if($icon == 'fa-font-awesome'){echo 'selected';}?> value='fa-font-awesome'>&#xf2b4; fa-font-awesome</option>
        <option <?php if($icon == 'fa-fonticons'){echo 'selected';}?> value='fa-fonticons'>&#xf280; fa-fonticons</option>
        <option <?php if($icon == 'fa-fort-awesome'){echo 'selected';}?> value='fa-fort-awesome'>&#xf286; fa-fort-awesome</option>
        <option <?php if($icon == 'fa-forumbee'){echo 'selected';}?> value='fa-forumbee'>&#xf211; fa-forumbee</option>
        <option <?php if($icon == 'fa-forward'){echo 'selected';}?> value='fa-forward'>&#xf04e; fa-forward</option>
        <option <?php if($icon == 'fa-foursquare'){echo 'selected';}?> value='fa-foursquare'>&#xf180; fa-foursquare</option>
        <option <?php if($icon == 'fa-free-code-camp'){echo 'selected';}?> value='fa-free-code-camp'>&#xf2c5; fa-free-code-camp</option>
        <option <?php if($icon == 'fa-frown-o'){echo 'selected';}?> value='fa-frown-o'>&#xf119; fa-frown-o</option>
        <option <?php if($icon == 'fa-futbol-o'){echo 'selected';}?> value='fa-futbol-o'>&#xf1e3; fa-futbol-o</option>
        <option <?php if($icon == 'fa-gamepad'){echo 'selected';}?> value='fa-gamepad'>&#xf11b; fa-gamepad</option>
        <option <?php if($icon == 'fa-gavel'){echo 'selected';}?> value='fa-gavel'>&#xf0e3; fa-gavel</option>
        <option <?php if($icon == 'fa-gbp'){echo 'selected';}?> value='fa-gbp'>&#xf154; fa-gbp</option>
        <option <?php if($icon == 'fa-ge'){echo 'selected';}?> value='fa-ge'>&#xf1d1; fa-ge</option>
        <option <?php if($icon == 'fa-gear'){echo 'selected';}?> value='fa-gear'>&#xf013; fa-gear</option>
        <option <?php if($icon == 'fa-gears'){echo 'selected';}?> value='fa-gears'>&#xf085; fa-gears</option>
        <option <?php if($icon == 'fa-genderless'){echo 'selected';}?> value='fa-genderless'>&#xf22d; fa-genderless</option>
        <option <?php if($icon == 'fa-get-pocket'){echo 'selected';}?> value='fa-get-pocket'>&#xf265; fa-get-pocket</option>
        <option <?php if($icon == 'fa-gg'){echo 'selected';}?> value='fa-gg'>&#xf260; fa-gg</option>
        <option <?php if($icon == 'fa-gg-circle'){echo 'selected';}?> value='fa-gg-circle'>&#xf261; fa-gg-circle</option>
        <option <?php if($icon == 'fa-gift'){echo 'selected';}?> value='fa-gift'>&#xf06b; fa-gift</option>
        <option <?php if($icon == 'fa-git'){echo 'selected';}?> value='fa-git'>&#xf1d3; fa-git</option>
        <option <?php if($icon == 'fa-git-square'){echo 'selected';}?> value='fa-git-square'>&#xf1d2; fa-git-square</option>
        <option <?php if($icon == 'fa-github'){echo 'selected';}?> value='fa-github'>&#xf09b; fa-github</option>
        <option <?php if($icon == 'fa-github-alt'){echo 'selected';}?> value='fa-github-alt'>&#xf113; fa-github-alt</option>
        <option <?php if($icon == 'fa-github-square'){echo 'selected';}?> value='fa-github-square'>&#xf092; fa-github-square</option>
        <option <?php if($icon == 'fa-gitlab'){echo 'selected';}?> value='fa-gitlab'>&#xf296; fa-gitlab</option>
        <option <?php if($icon == 'fa-gittip'){echo 'selected';}?> value='fa-gittip'>&#xf184; fa-gittip</option>
        <option <?php if($icon == 'fa-glass'){echo 'selected';}?> value='fa-glass'>&#xf000; fa-glass</option>
        <option <?php if($icon == 'fa-glide'){echo 'selected';}?> value='fa-glide'>&#xf2a5; fa-glide</option>
        <option <?php if($icon == 'fa-glide-g'){echo 'selected';}?> value='fa-glide-g'>&#xf2a6; fa-glide-g</option>
        <option <?php if($icon == 'fa-globe'){echo 'selected';}?> value='fa-globe'>&#xf0ac; fa-globe</option>
        <option <?php if($icon == 'fa-google'){echo 'selected';}?> value='fa-google'>&#xf1a0; fa-google</option>
        <option <?php if($icon == 'fa-google-plus'){echo 'selected';}?> value='fa-google-plus'>&#xf0d5; fa-google-plus</option>
        <option <?php if($icon == 'fa-google-plus-circle'){echo 'selected';}?> value='fa-google-plus-circle'>&#xf2b3; fa-google-plus-circle</option>
        <option <?php if($icon == 'fa-google-plus-official'){echo 'selected';}?> value='fa-google-plus-official'>&#xf2b3; fa-google-plus-official</option>
        <option <?php if($icon == 'fa-google-plus-square'){echo 'selected';}?> value='fa-google-plus-square'>&#xf0d4; fa-google-plus-square</option>
        <option <?php if($icon == 'fa-google-wallet'){echo 'selected';}?> value='fa-google-wallet'>&#xf1ee; fa-google-wallet</option>
        <option <?php if($icon == 'fa-graduation-cap'){echo 'selected';}?> value='fa-graduation-cap'>&#xf19d; fa-graduation-cap</option>
        <option <?php if($icon == 'fa-gratipay'){echo 'selected';}?> value='fa-gratipay'>&#xf184; fa-gratipay</option>
        <option <?php if($icon == 'fa-grav'){echo 'selected';}?> value='fa-grav'>&#xf2d6; fa-grav</option>
        <option <?php if($icon == 'fa-group'){echo 'selected';}?> value='fa-group'>&#xf0c0; fa-group</option>
        <option <?php if($icon == 'fa-h-square'){echo 'selected';}?> value='fa-h-square'>&#xf0fd; fa-h-square</option>
        <option <?php if($icon == 'fa-hacker-news'){echo 'selected';}?> value='fa-hacker-news'>&#xf1d4; fa-hacker-news</option>
        <option <?php if($icon == 'fa-hand-grab-o'){echo 'selected';}?> value='fa-hand-grab-o'>&#xf255; fa-hand-grab-o</option>
        <option <?php if($icon == 'fa-hand-lizard-o'){echo 'selected';}?> value='fa-hand-lizard-o'>&#xf258; fa-hand-lizard-o</option>
        <option <?php if($icon == 'fa-hand-o-down'){echo 'selected';}?> value='fa-hand-o-down'>&#xf0a7; fa-hand-o-down</option>
        <option <?php if($icon == 'fa-hand-o-left'){echo 'selected';}?> value='fa-hand-o-left'>&#xf0a5; fa-hand-o-left</option>
        <option <?php if($icon == 'fa-hand-o-right'){echo 'selected';}?> value='fa-hand-o-right'>&#xf0a4; fa-hand-o-right</option>
        <option <?php if($icon == 'fa-hand-o-up'){echo 'selected';}?> value='fa-hand-o-up'>&#xf0a6; fa-hand-o-up</option>
        <option <?php if($icon == 'fa-hand-paper-o'){echo 'selected';}?> value='fa-hand-paper-o'>&#xf256; fa-hand-paper-o</option>
        <option <?php if($icon == 'fa-hand-peace-o'){echo 'selected';}?> value='fa-hand-peace-o'>&#xf25b; fa-hand-peace-o</option>
        <option <?php if($icon == 'fa-hand-pointer-o'){echo 'selected';}?> value='fa-hand-pointer-o'>&#xf25a; fa-hand-pointer-o</option>
        <option <?php if($icon == 'fa-hand-rock-o'){echo 'selected';}?> value='fa-hand-rock-o'>&#xf255; fa-hand-rock-o</option>
        <option <?php if($icon == 'fa-hand-scissors-o'){echo 'selected';}?> value='fa-hand-scissors-o'>&#xf257; fa-hand-scissors-o</option>
        <option <?php if($icon == 'fa-hand-spock-o'){echo 'selected';}?> value='fa-hand-spock-o'>&#xf259; fa-hand-spock-o</option>
        <option <?php if($icon == 'fa-hand-stop-o'){echo 'selected';}?> value='fa-hand-stop-o'>&#xf256; fa-hand-stop-o</option>
        <option <?php if($icon == 'fa-handshake-o'){echo 'selected';}?> value='fa-handshake-o'>&#xf2b5; fa-handshake-o</option>
        <option <?php if($icon == 'fa-hard-of-hearing'){echo 'selected';}?> value='fa-hard-of-hearing'>&#xf2a4; fa-hard-of-hearing</option>
        <option <?php if($icon == 'fa-hashtag'){echo 'selected';}?> value='fa-hashtag'>&#xf292; fa-hashtag</option>
        <option <?php if($icon == 'fa-hdd-o'){echo 'selected';}?> value='fa-hdd-o'>&#xf0a0; fa-hdd-o</option>
        <option <?php if($icon == 'fa-header'){echo 'selected';}?> value='fa-header'>&#xf1dc; fa-header</option>
        <option <?php if($icon == 'fa-headphones'){echo 'selected';}?> value='fa-headphones'>&#xf025; fa-headphones</option>
        <option <?php if($icon == 'fa-heart'){echo 'selected';}?> value='fa-heart'>&#xf004; fa-heart</option>
        <option <?php if($icon == 'fa-heart-o'){echo 'selected';}?> value='fa-heart-o'>&#xf08a; fa-heart-o</option>
        <option <?php if($icon == 'fa-heartbeat'){echo 'selected';}?> value='fa-heartbeat'>&#xf21e; fa-heartbeat</option>
        <option <?php if($icon == 'fa-history'){echo 'selected';}?> value='fa-history'>&#xf1da; fa-history</option>
        <option <?php if($icon == 'fa-home'){echo 'selected';}?> value='fa-home'>&#xf015; fa-home</option>
        <option <?php if($icon == 'fa-hospital-o'){echo 'selected';}?> value='fa-hospital-o'>&#xf0f8; fa-hospital-o</option>
        <option <?php if($icon == 'fa-hotel'){echo 'selected';}?> value='fa-hotel'>&#xf236; fa-hotel</option>
        <option <?php if($icon == 'fa-hourglass'){echo 'selected';}?> value='fa-hourglass'>&#xf254; fa-hourglass</option>
        <option <?php if($icon == 'fa-hourglass-1'){echo 'selected';}?> value='fa-hourglass-1'>&#xf251; fa-hourglass-1</option>
        <option <?php if($icon == 'fa-hourglass-2'){echo 'selected';}?> value='fa-hourglass-2'>&#xf252; fa-hourglass-2</option>
        <option <?php if($icon == 'fa-hourglass-3'){echo 'selected';}?> value='fa-hourglass-3'>&#xf253; fa-hourglass-3</option>
        <option <?php if($icon == 'fa-hourglass-end'){echo 'selected';}?> value='fa-hourglass-end'>&#xf253; fa-hourglass-end</option>
        <option <?php if($icon == 'fa-hourglass-half'){echo 'selected';}?> value='fa-hourglass-half'>&#xf252; fa-hourglass-half</option>
        <option <?php if($icon == 'fa-hourglass-o'){echo 'selected';}?> value='fa-hourglass-o'>&#xf250; fa-hourglass-o</option>
        <option <?php if($icon == 'fa-hourglass-start'){echo 'selected';}?> value='fa-hourglass-start'>&#xf251; fa-hourglass-start</option>
        <option <?php if($icon == 'fa-houzz'){echo 'selected';}?> value='fa-houzz'>&#xf27c; fa-houzz</option>
        <option <?php if($icon == 'fa-html5'){echo 'selected';}?> value='fa-html5'>&#xf13b; fa-html5</option>
        <option <?php if($icon == 'fa-i-cursor'){echo 'selected';}?> value='fa-i-cursor'>&#xf246; fa-i-cursor</option>
        <option <?php if($icon == 'fa-id-badge'){echo 'selected';}?> value='fa-id-badge'>&#xf2c1; fa-id-badge</option>
        <option <?php if($icon == 'fa-id-card'){echo 'selected';}?> value='fa-id-card'>&#xf2c2; fa-id-card</option>
        <option <?php if($icon == 'fa-id-card-o'){echo 'selected';}?> value='fa-id-card-o'>&#xf2c3; fa-id-card-o</option>
        <option <?php if($icon == 'fa-ils'){echo 'selected';}?> value='fa-ils'>&#xf20b; fa-ils</option>
        <option <?php if($icon == 'fa-image'){echo 'selected';}?> value='fa-image'>&#xf03e; fa-image</option>
        <option <?php if($icon == 'fa-imdb'){echo 'selected';}?> value='fa-imdb'>&#xf2d8; fa-imdb</option>
        <option <?php if($icon == 'fa-inbox'){echo 'selected';}?> value='fa-inbox'>&#xf01c; fa-inbox</option>
        <option <?php if($icon == 'fa-indent'){echo 'selected';}?> value='fa-indent'>&#xf03c; fa-indent</option>
        <option <?php if($icon == 'fa-industry'){echo 'selected';}?> value='fa-industry'>&#xf275; fa-industry</option>
        <option <?php if($icon == 'fa-info'){echo 'selected';}?> value='fa-info'>&#xf129; fa-info</option>
        <option <?php if($icon == 'fa-info-circle'){echo 'selected';}?> value='fa-info-circle'>&#xf05a; fa-info-circle</option>
        <option <?php if($icon == 'fa-inr'){echo 'selected';}?> value='fa-inr'>&#xf156; fa-inr</option>
        <option <?php if($icon == 'fa-instagram'){echo 'selected';}?> value='fa-instagram'>&#xf16d; fa-instagram</option>
        <option <?php if($icon == 'fa-institution'){echo 'selected';}?> value='fa-institution'>&#xf19c; fa-institution</option>
        <option <?php if($icon == 'fa-internet-explorer'){echo 'selected';}?> value='fa-internet-explorer'>&#xf26b; fa-internet-explorer</option>
        <option <?php if($icon == 'fa-intersex'){echo 'selected';}?> value='fa-intersex'>&#xf224; fa-intersex</option>
        <option <?php if($icon == 'fa-ioxhost'){echo 'selected';}?> value='fa-ioxhost'>&#xf208; fa-ioxhost</option>
        <option <?php if($icon == 'fa-italic'){echo 'selected';}?> value='fa-italic'>&#xf033; fa-italic</option>
        <option <?php if($icon == 'fa-joomla'){echo 'selected';}?> value='fa-joomla'>&#xf1aa; fa-joomla</option>
        <option <?php if($icon == 'fa-jpy'){echo 'selected';}?> value='fa-jpy'>&#xf157; fa-jpy</option>
        <option <?php if($icon == 'fa-jsfiddle'){echo 'selected';}?> value='fa-jsfiddle'>&#xf1cc; fa-jsfiddle</option>
        <option <?php if($icon == 'fa-key'){echo 'selected';}?> value='fa-key'>&#xf084; fa-key</option>
        <option <?php if($icon == 'fa-keyboard-o'){echo 'selected';}?> value='fa-keyboard-o'>&#xf11c; fa-keyboard-o</option>
        <option <?php if($icon == 'fa-krw'){echo 'selected';}?> value='fa-krw'>&#xf159; fa-krw</option>
        <option <?php if($icon == 'fa-language'){echo 'selected';}?> value='fa-language'>&#xf1ab; fa-language</option>
        <option <?php if($icon == 'fa-laptop'){echo 'selected';}?> value='fa-laptop'>&#xf109; fa-laptop</option>
        <option <?php if($icon == 'fa-lastfm'){echo 'selected';}?> value='fa-lastfm'>&#xf202; fa-lastfm</option>
        <option <?php if($icon == 'fa-lastfm-square'){echo 'selected';}?> value='fa-lastfm-square'>&#xf203; fa-lastfm-square</option>
        <option <?php if($icon == 'fa-leaf'){echo 'selected';}?> value='fa-leaf'>&#xf06c; fa-leaf</option>
        <option <?php if($icon == 'fa-leanpub'){echo 'selected';}?> value='fa-leanpub'>&#xf212; fa-leanpub</option>
        <option <?php if($icon == 'fa-legal'){echo 'selected';}?> value='fa-legal'>&#xf0e3; fa-legal</option>
        <option <?php if($icon == 'fa-lemon-o'){echo 'selected';}?> value='fa-lemon-o'>&#xf094; fa-lemon-o</option>
        <option <?php if($icon == 'fa-level-down'){echo 'selected';}?> value='fa-level-down'>&#xf149; fa-level-down</option>
        <option <?php if($icon == 'fa-level-up'){echo 'selected';}?> value='fa-level-up'>&#xf148; fa-level-up</option>
        <option <?php if($icon == 'fa-life-bouy'){echo 'selected';}?> value='fa-life-bouy'>&#xf1cd; fa-life-bouy</option>
        <option <?php if($icon == 'fa-life-buoy'){echo 'selected';}?> value='fa-life-buoy'>&#xf1cd; fa-life-buoy</option>
        <option <?php if($icon == 'fa-life-ring'){echo 'selected';}?> value='fa-life-ring'>&#xf1cd; fa-life-ring</option>
        <option <?php if($icon == 'fa-life-saver'){echo 'selected';}?> value='fa-life-saver'>&#xf1cd; fa-life-saver</option>
        <option <?php if($icon == 'fa-lightbulb-o'){echo 'selected';}?> value='fa-lightbulb-o'>&#xf0eb; fa-lightbulb-o</option>
        <option <?php if($icon == 'fa-line-chart'){echo 'selected';}?> value='fa-line-chart'>&#xf201; fa-line-chart</option>
        <option <?php if($icon == 'fa-link'){echo 'selected';}?> value='fa-link'>&#xf0c1; fa-link</option>
        <option <?php if($icon == 'fa-linkedin'){echo 'selected';}?> value='fa-linkedin'>&#xf0e1; fa-linkedin</option>
        <option <?php if($icon == 'fa-linkedin-square'){echo 'selected';}?> value='fa-linkedin-square'>&#xf08c; fa-linkedin-square</option>
        <option <?php if($icon == 'fa-linode'){echo 'selected';}?> value='fa-linode'>&#xf2b8; fa-linode</option>
        <option <?php if($icon == 'fa-linux'){echo 'selected';}?> value='fa-linux'>&#xf17c; fa-linux</option>
        <option <?php if($icon == 'fa-list'){echo 'selected';}?> value='fa-list'>&#xf03a; fa-list</option>
        <option <?php if($icon == 'fa-list-alt'){echo 'selected';}?> value='fa-list-alt'>&#xf022; fa-list-alt</option>
        <option <?php if($icon == 'fa-list-ol'){echo 'selected';}?> value='fa-list-ol'>&#xf0cb; fa-list-ol</option>
        <option <?php if($icon == 'fa-list-ul'){echo 'selected';}?> value='fa-list-ul'>&#xf0ca; fa-list-ul</option>
        <option <?php if($icon == 'fa-location-arrow'){echo 'selected';}?> value='fa-location-arrow'>&#xf124; fa-location-arrow</option>
        <option <?php if($icon == 'fa-lock'){echo 'selected';}?> value='fa-lock'>&#xf023; fa-lock</option>
        <option <?php if($icon == 'fa-long-arrow-down'){echo 'selected';}?> value='fa-long-arrow-down'>&#xf175; fa-long-arrow-down</option>
        <option <?php if($icon == 'fa-long-arrow-left'){echo 'selected';}?> value='fa-long-arrow-left'>&#xf177; fa-long-arrow-left</option>
        <option <?php if($icon == 'fa-long-arrow-right'){echo 'selected';}?> value='fa-long-arrow-right'>&#xf178; fa-long-arrow-right</option>
        <option <?php if($icon == 'fa-long-arrow-up'){echo 'selected';}?> value='fa-long-arrow-up'>&#xf176; fa-long-arrow-up</option>
        <option <?php if($icon == 'fa-low-vision'){echo 'selected';}?> value='fa-low-vision'>&#xf2a8; fa-low-vision</option>
        <option <?php if($icon == 'fa-magic'){echo 'selected';}?> value='fa-magic'>&#xf0d0; fa-magic</option>
        <option <?php if($icon == 'fa-magnet'){echo 'selected';}?> value='fa-magnet'>&#xf076; fa-magnet</option>
        <option <?php if($icon == 'fa-mail-forward'){echo 'selected';}?> value='fa-mail-forward'>&#xf064; fa-mail-forward</option>
        <option <?php if($icon == 'fa-mail-reply'){echo 'selected';}?> value='fa-mail-reply'>&#xf112; fa-mail-reply</option>
        <option <?php if($icon == 'fa-mail-reply-all'){echo 'selected';}?> value='fa-mail-reply-all'>&#xf122; fa-mail-reply-all</option>
        <option <?php if($icon == 'fa-male'){echo 'selected';}?> value='fa-male'>&#xf183; fa-male</option>
        <option <?php if($icon == 'fa-map'){echo 'selected';}?> value='fa-map'>&#xf279; fa-map</option>
        <option <?php if($icon == 'fa-map-marker'){echo 'selected';}?> value='fa-map-marker'>&#xf041; fa-map-marker</option>
        <option <?php if($icon == 'fa-map-o'){echo 'selected';}?> value='fa-map-o'>&#xf278; fa-map-o</option>
        <option <?php if($icon == 'fa-map-pin'){echo 'selected';}?> value='fa-map-pin'>&#xf276; fa-map-pin</option>
        <option <?php if($icon == 'fa-map-signs'){echo 'selected';}?> value='fa-map-signs'>&#xf277; fa-map-signs</option>
        <option <?php if($icon == 'fa-mars'){echo 'selected';}?> value='fa-mars'>&#xf222; fa-mars</option>
        <option <?php if($icon == 'fa-mars-double'){echo 'selected';}?> value='fa-mars-double'>&#xf227; fa-mars-double</option>
        <option <?php if($icon == 'fa-mars-stroke'){echo 'selected';}?> value='fa-mars-stroke'>&#xf229; fa-mars-stroke</option>
        <option <?php if($icon == 'fa-mars-stroke-h'){echo 'selected';}?> value='fa-mars-stroke-h'>&#xf22b; fa-mars-stroke-h</option>
        <option <?php if($icon == 'fa-mars-stroke-v'){echo 'selected';}?> value='fa-mars-stroke-v'>&#xf22a; fa-mars-stroke-v</option>
        <option <?php if($icon == 'fa-maxcdn'){echo 'selected';}?> value='fa-maxcdn'>&#xf136; fa-maxcdn</option>
        <option <?php if($icon == 'fa-meanpath'){echo 'selected';}?> value='fa-meanpath'>&#xf20c; fa-meanpath</option>
        <option <?php if($icon == 'fa-medium'){echo 'selected';}?> value='fa-medium'>&#xf23a; fa-medium</option>
        <option <?php if($icon == 'fa-medkit'){echo 'selected';}?> value='fa-medkit'>&#xf0fa; fa-medkit</option>
        <option <?php if($icon == 'fa-meetup'){echo 'selected';}?> value='fa-meetup'>&#xf2e0; fa-meetup</option>
        <option <?php if($icon == 'fa-meh-o'){echo 'selected';}?> value='fa-meh-o'>&#xf11a; fa-meh-o</option>
        <option <?php if($icon == 'fa-mercury'){echo 'selected';}?> value='fa-mercury'>&#xf223; fa-mercury</option>
        <option <?php if($icon == 'fa-microchip'){echo 'selected';}?> value='fa-microchip'>&#xf2db; fa-microchip</option>
        <option <?php if($icon == 'fa-microphone'){echo 'selected';}?> value='fa-microphone'>&#xf130; fa-microphone</option>
        <option <?php if($icon == 'fa-microphone-slash'){echo 'selected';}?> value='fa-microphone-slash'>&#xf131; fa-microphone-slash</option>
        <option <?php if($icon == 'fa-minus'){echo 'selected';}?> value='fa-minus'>&#xf068; fa-minus</option>
        <option <?php if($icon == 'fa-minus-circle'){echo 'selected';}?> value='fa-minus-circle'>&#xf056; fa-minus-circle</option>
        <option <?php if($icon == 'fa-minus-square'){echo 'selected';}?> value='fa-minus-square'>&#xf146; fa-minus-square</option>
        <option <?php if($icon == 'fa-minus-square-o'){echo 'selected';}?> value='fa-minus-square-o'>&#xf147; fa-minus-square-o</option>
        <option <?php if($icon == 'fa-mixcloud'){echo 'selected';}?> value='fa-mixcloud'>&#xf289; fa-mixcloud</option>
        <option <?php if($icon == 'fa-mobile'){echo 'selected';}?> value='fa-mobile'>&#xf10b; fa-mobile</option>
        <option <?php if($icon == 'fa-mobile-phone'){echo 'selected';}?> value='fa-mobile-phone'>&#xf10b; fa-mobile-phone</option>
        <option <?php if($icon == 'fa-modx'){echo 'selected';}?> value='fa-modx'>&#xf285; fa-modx</option>
        <option <?php if($icon == 'fa-money'){echo 'selected';}?> value='fa-money'>&#xf0d6; fa-money</option>
        <option <?php if($icon == 'fa-moon-o'){echo 'selected';}?> value='fa-moon-o'>&#xf186; fa-moon-o</option>
        <option <?php if($icon == 'fa-mortar-board'){echo 'selected';}?> value='fa-mortar-board'>&#xf19d; fa-mortar-board</option>
        <option <?php if($icon == 'fa-motorcycle'){echo 'selected';}?> value='fa-motorcycle'>&#xf21c; fa-motorcycle</option>
        <option <?php if($icon == 'fa-mouse-pointer'){echo 'selected';}?> value='fa-mouse-pointer'>&#xf245; fa-mouse-pointer</option>
        <option <?php if($icon == 'fa-music'){echo 'selected';}?> value='fa-music'>&#xf001; fa-music</option>
        <option <?php if($icon == 'fa-navicon'){echo 'selected';}?> value='fa-navicon'>&#xf0c9; fa-navicon</option>
        <option <?php if($icon == 'fa-neuter'){echo 'selected';}?> value='fa-neuter'>&#xf22c; fa-neuter</option>
        <option <?php if($icon == 'fa-newspaper-o'){echo 'selected';}?> value='fa-newspaper-o'>&#xf1ea; fa-newspaper-o</option>
        <option <?php if($icon == 'fa-object-group'){echo 'selected';}?> value='fa-object-group'>&#xf247; fa-object-group</option>
        <option <?php if($icon == 'fa-object-ungroup'){echo 'selected';}?> value='fa-object-ungroup'>&#xf248; fa-object-ungroup</option>
        <option <?php if($icon == 'fa-odnoklassniki'){echo 'selected';}?> value='fa-odnoklassniki'>&#xf263; fa-odnoklassniki</option>
        <option <?php if($icon == 'fa-odnoklassniki-square'){echo 'selected';}?> value='fa-odnoklassniki-square'>&#xf264; fa-odnoklassniki-square</option>
        <option <?php if($icon == 'fa-opencart'){echo 'selected';}?> value='fa-opencart'>&#xf23d; fa-opencart</option>
        <option <?php if($icon == 'fa-openid'){echo 'selected';}?> value='fa-openid'>&#xf19b; fa-openid</option>
        <option <?php if($icon == 'fa-opera'){echo 'selected';}?> value='fa-opera'>&#xf26a; fa-opera</option>
        <option <?php if($icon == 'fa-optin-monster'){echo 'selected';}?> value='fa-optin-monster'>&#xf23c; fa-optin-monster</option>
        <option <?php if($icon == 'fa-outdent'){echo 'selected';}?> value='fa-outdent'>&#xf03b; fa-outdent</option>
        <option <?php if($icon == 'fa-pagelines'){echo 'selected';}?> value='fa-pagelines'>&#xf18c; fa-pagelines</option>
        <option <?php if($icon == 'fa-paint-brush'){echo 'selected';}?> value='fa-paint-brush'>&#xf1fc; fa-paint-brush</option>
        <option <?php if($icon == 'fa-paper-plane'){echo 'selected';}?> value='fa-paper-plane'>&#xf1d8; fa-paper-plane</option>
        <option <?php if($icon == 'fa-paper-plane-o'){echo 'selected';}?> value='fa-paper-plane-o'>&#xf1d9; fa-paper-plane-o</option>
        <option <?php if($icon == 'fa-paperclip'){echo 'selected';}?> value='fa-paperclip'>&#xf0c6; fa-paperclip</option>
        <option <?php if($icon == 'fa-paragraph'){echo 'selected';}?> value='fa-paragraph'>&#xf1dd; fa-paragraph</option>
        <option <?php if($icon == 'fa-paste'){echo 'selected';}?> value='fa-paste'>&#xf0ea; fa-paste</option>
        <option <?php if($icon == 'fa-pause'){echo 'selected';}?> value='fa-pause'>&#xf04c; fa-pause</option>
        <option <?php if($icon == 'fa-pause-circle'){echo 'selected';}?> value='fa-pause-circle'>&#xf28b; fa-pause-circle</option>
        <option <?php if($icon == 'fa-pause-circle-o'){echo 'selected';}?> value='fa-pause-circle-o'>&#xf28c; fa-pause-circle-o</option>
        <option <?php if($icon == 'fa-paw'){echo 'selected';}?> value='fa-paw'>&#xf1b0; fa-paw</option>
        <option <?php if($icon == 'fa-paypal'){echo 'selected';}?> value='fa-paypal'>&#xf1ed; fa-paypal</option>
        <option <?php if($icon == 'fa-pencil'){echo 'selected';}?> value='fa-pencil'>&#xf040; fa-pencil</option>
        <option <?php if($icon == 'fa-pencil-square'){echo 'selected';}?> value='fa-pencil-square'>&#xf14b; fa-pencil-square</option>
        <option <?php if($icon == 'fa-pencil-square-o'){echo 'selected';}?> value='fa-pencil-square-o'>&#xf044; fa-pencil-square-o</option>
        <option <?php if($icon == 'fa-percent'){echo 'selected';}?> value='fa-percent'>&#xf295; fa-percent</option>
        <option <?php if($icon == 'fa-phone'){echo 'selected';}?> value='fa-phone'>&#xf095; fa-phone</option>
        <option <?php if($icon == 'fa-phone-square'){echo 'selected';}?> value='fa-phone-square'>&#xf098; fa-phone-square</option>
        <option <?php if($icon == 'fa-photo'){echo 'selected';}?> value='fa-photo'>&#xf03e; fa-photo</option>
        <option <?php if($icon == 'fa-picture-o'){echo 'selected';}?> value='fa-picture-o'>&#xf03e; fa-picture-o</option>
        <option <?php if($icon == 'fa-pie-chart'){echo 'selected';}?> value='fa-pie-chart'>&#xf200; fa-pie-chart</option>
        <option <?php if($icon == 'fa-pied-piper'){echo 'selected';}?> value='fa-pied-piper'>&#xf2ae; fa-pied-piper</option>
        <option <?php if($icon == 'fa-pied-piper-alt'){echo 'selected';}?> value='fa-pied-piper-alt'>&#xf1a8; fa-pied-piper-alt</option>
        <option <?php if($icon == 'fa-pied-piper-pp'){echo 'selected';}?> value='fa-pied-piper-pp'>&#xf1a7; fa-pied-piper-pp</option>
        <option <?php if($icon == 'fa-pinterest'){echo 'selected';}?> value='fa-pinterest'>&#xf0d2; fa-pinterest</option>
        <option <?php if($icon == 'fa-pinterest-p'){echo 'selected';}?> value='fa-pinterest-p'>&#xf231; fa-pinterest-p</option>
        <option <?php if($icon == 'fa-pinterest-square'){echo 'selected';}?> value='fa-pinterest-square'>&#xf0d3; fa-pinterest-square</option>
        <option <?php if($icon == 'fa-plane'){echo 'selected';}?> value='fa-plane'>&#xf072; fa-plane</option>
        <option <?php if($icon == 'fa-play'){echo 'selected';}?> value='fa-play'>&#xf04b; fa-play</option>
        <option <?php if($icon == 'fa-play-circle'){echo 'selected';}?> value='fa-play-circle'>&#xf144; fa-play-circle</option>
        <option <?php if($icon == 'fa-play-circle-o'){echo 'selected';}?> value='fa-play-circle-o'>&#xf01d; fa-play-circle-o</option>
        <option <?php if($icon == 'fa-plug'){echo 'selected';}?> value='fa-plug'>&#xf1e6; fa-plug</option>
        <option <?php if($icon == 'fa-plus'){echo 'selected';}?> value='fa-plus'>&#xf067; fa-plus</option>
        <option <?php if($icon == 'fa-plus-circle'){echo 'selected';}?> value='fa-plus-circle'>&#xf055; fa-plus-circle</option>
        <option <?php if($icon == 'fa-plus-square'){echo 'selected';}?> value='fa-plus-square'>&#xf0fe; fa-plus-square</option>
        <option <?php if($icon == 'fa-plus-square-o'){echo 'selected';}?> value='fa-plus-square-o'>&#xf196; fa-plus-square-o</option>
        <option <?php if($icon == 'fa-podcast'){echo 'selected';}?> value='fa-podcast'>&#xf2ce; fa-podcast</option>
        <option <?php if($icon == 'fa-power-off'){echo 'selected';}?> value='fa-power-off'>&#xf011; fa-power-off</option>
        <option <?php if($icon == 'fa-print'){echo 'selected';}?> value='fa-print'>&#xf02f; fa-print</option>
        <option <?php if($icon == 'fa-product-hunt'){echo 'selected';}?> value='fa-product-hunt'>&#xf288; fa-product-hunt</option>
        <option <?php if($icon == 'fa-puzzle-piece'){echo 'selected';}?> value='fa-puzzle-piece'>&#xf12e; fa-puzzle-piece</option>
        <option <?php if($icon == 'fa-qq'){echo 'selected';}?> value='fa-qq'>&#xf1d6; fa-qq</option>
        <option <?php if($icon == 'fa-qrcode'){echo 'selected';}?> value='fa-qrcode'>&#xf029; fa-qrcode</option>
        <option <?php if($icon == 'fa-question'){echo 'selected';}?> value='fa-question'>&#xf128; fa-question</option>
        <option <?php if($icon == 'fa-question-circle'){echo 'selected';}?> value='fa-question-circle'>&#xf059; fa-question-circle</option>
        <option <?php if($icon == 'fa-question-circle-o'){echo 'selected';}?> value='fa-question-circle-o'>&#xf29c; fa-question-circle-o</option>
        <option <?php if($icon == 'fa-quora'){echo 'selected';}?> value='fa-quora'>&#xf2c4; fa-quora</option>
        <option <?php if($icon == 'fa-quote-left'){echo 'selected';}?> value='fa-quote-left'>&#xf10d; fa-quote-left</option>
        <option <?php if($icon == 'fa-quote-right'){echo 'selected';}?> value='fa-quote-right'>&#xf10e; fa-quote-right</option>
        <option <?php if($icon == 'fa-ra'){echo 'selected';}?> value='fa-ra'>&#xf1d0; fa-ra</option>
        <option <?php if($icon == 'fa-random'){echo 'selected';}?> value='fa-random'>&#xf074; fa-random</option>
        <option <?php if($icon == 'fa-ravelry'){echo 'selected';}?> value='fa-ravelry'>&#xf2d9; fa-ravelry</option>
        <option <?php if($icon == 'fa-rebel'){echo 'selected';}?> value='fa-rebel'>&#xf1d0; fa-rebel</option>
        <option <?php if($icon == 'fa-recycle'){echo 'selected';}?> value='fa-recycle'>&#xf1b8; fa-recycle</option>
        <option <?php if($icon == 'fa-reddit'){echo 'selected';}?> value='fa-reddit'>&#xf1a1; fa-reddit</option>
        <option <?php if($icon == 'fa-reddit-alien'){echo 'selected';}?> value='fa-reddit-alien'>&#xf281; fa-reddit-alien</option>
        <option <?php if($icon == 'fa-reddit-square'){echo 'selected';}?> value='fa-reddit-square'>&#xf1a2; fa-reddit-square</option>
        <option <?php if($icon == 'fa-refresh'){echo 'selected';}?> value='fa-refresh'>&#xf021; fa-refresh</option>
        <option <?php if($icon == 'fa-registered'){echo 'selected';}?> value='fa-registered'>&#xf25d; fa-registered</option>
        <option <?php if($icon == 'fa-remove'){echo 'selected';}?> value='fa-remove'>&#xf00d; fa-remove</option>
        <option <?php if($icon == 'fa-renren'){echo 'selected';}?> value='fa-renren'>&#xf18b; fa-renren</option>
        <option <?php if($icon == 'fa-reorder'){echo 'selected';}?> value='fa-reorder'>&#xf0c9; fa-reorder</option>
        <option <?php if($icon == 'fa-repeat'){echo 'selected';}?> value='fa-repeat'>&#xf01e; fa-repeat</option>
        <option <?php if($icon == 'fa-reply'){echo 'selected';}?> value='fa-reply'>&#xf112; fa-reply</option>
        <option <?php if($icon == 'fa-reply-all'){echo 'selected';}?> value='fa-reply-all'>&#xf122; fa-reply-all</option>
        <option <?php if($icon == 'fa-resistance'){echo 'selected';}?> value='fa-resistance'>&#xf1d0; fa-resistance</option>
        <option <?php if($icon == 'fa-retweet'){echo 'selected';}?> value='fa-retweet'>&#xf079; fa-retweet</option>
        <option <?php if($icon == 'fa-rmb'){echo 'selected';}?> value='fa-rmb'>&#xf157; fa-rmb</option>
        <option <?php if($icon == 'fa-road'){echo 'selected';}?> value='fa-road'>&#xf018; fa-road</option>
        <option <?php if($icon == 'fa-rocket'){echo 'selected';}?> value='fa-rocket'>&#xf135; fa-rocket</option>
        <option <?php if($icon == 'fa-rotate-left'){echo 'selected';}?> value='fa-rotate-left'>&#xf0e2; fa-rotate-left</option>
        <option <?php if($icon == 'fa-rotate-right'){echo 'selected';}?> value='fa-rotate-right'>&#xf01e; fa-rotate-right</option>
        <option <?php if($icon == 'fa-rouble'){echo 'selected';}?> value='fa-rouble'>&#xf158; fa-rouble</option>
        <option <?php if($icon == 'fa-rss'){echo 'selected';}?> value='fa-rss'>&#xf09e; fa-rss</option>
        <option <?php if($icon == 'fa-rss-square'){echo 'selected';}?> value='fa-rss-square'>&#xf143; fa-rss-square</option>
        <option <?php if($icon == 'fa-rub'){echo 'selected';}?> value='fa-rub'>&#xf158; fa-rub</option>
        <option <?php if($icon == 'fa-ruble'){echo 'selected';}?> value='fa-ruble'>&#xf158; fa-ruble</option>
        <option <?php if($icon == 'fa-rupee'){echo 'selected';}?> value='fa-rupee'>&#xf156; fa-rupee</option>
        <option <?php if($icon == 'fa-s15'){echo 'selected';}?> value='fa-s15'>&#xf2cd; fa-s15</option>
        <option <?php if($icon == 'fa-safari'){echo 'selected';}?> value='fa-safari'>&#xf267; fa-safari</option>
        <option <?php if($icon == 'fa-save'){echo 'selected';}?> value='fa-save'>&#xf0c7; fa-save</option>
        <option <?php if($icon == 'fa-scissors'){echo 'selected';}?> value='fa-scissors'>&#xf0c4; fa-scissors</option>
        <option <?php if($icon == 'fa-scribd'){echo 'selected';}?> value='fa-scribd'>&#xf28a; fa-scribd</option>
        <option <?php if($icon == 'fa-search'){echo 'selected';}?> value='fa-search'>&#xf002; fa-search</option>
        <option <?php if($icon == 'fa-search-minus'){echo 'selected';}?> value='fa-search-minus'>&#xf010; fa-search-minus</option>
        <option <?php if($icon == 'fa-search-plus'){echo 'selected';}?> value='fa-search-plus'>&#xf00e; fa-search-plus</option>
        <option <?php if($icon == 'fa-sellsy'){echo 'selected';}?> value='fa-sellsy'>&#xf213; fa-sellsy</option>
        <option <?php if($icon == 'fa-send'){echo 'selected';}?> value='fa-send'>&#xf1d8; fa-send</option>
        <option <?php if($icon == 'fa-send-o'){echo 'selected';}?> value='fa-send-o'>&#xf1d9; fa-send-o</option>
        <option <?php if($icon == 'fa-server'){echo 'selected';}?> value='fa-server'>&#xf233; fa-server</option>
        <option <?php if($icon == 'fa-share'){echo 'selected';}?> value='fa-share'>&#xf064; fa-share</option>
        <option <?php if($icon == 'fa-share-alt'){echo 'selected';}?> value='fa-share-alt'>&#xf1e0; fa-share-alt</option>
        <option <?php if($icon == 'fa-share-alt-square'){echo 'selected';}?> value='fa-share-alt-square'>&#xf1e1; fa-share-alt-square</option>
        <option <?php if($icon == 'fa-share-square'){echo 'selected';}?> value='fa-share-square'>&#xf14d; fa-share-square</option>
        <option <?php if($icon == 'fa-share-square-o'){echo 'selected';}?> value='fa-share-square-o'>&#xf045; fa-share-square-o</option>
        <option <?php if($icon == 'fa-shekel'){echo 'selected';}?> value='fa-shekel'>&#xf20b; fa-shekel</option>
        <option <?php if($icon == 'fa-sheqel'){echo 'selected';}?> value='fa-sheqel'>&#xf20b; fa-sheqel</option>
        <option <?php if($icon == 'fa-shield'){echo 'selected';}?> value='fa-shield'>&#xf132; fa-shield</option>
        <option <?php if($icon == 'fa-ship'){echo 'selected';}?> value='fa-ship'>&#xf21a; fa-ship</option>
        <option <?php if($icon == 'fa-shirtsinbulk'){echo 'selected';}?> value='fa-shirtsinbulk'>&#xf214; fa-shirtsinbulk</option>
        <option <?php if($icon == 'fa-shopping-bag'){echo 'selected';}?> value='fa-shopping-bag'>&#xf290; fa-shopping-bag</option>
        <option <?php if($icon == 'fa-shopping-basket'){echo 'selected';}?> value='fa-shopping-basket'>&#xf291; fa-shopping-basket</option>
        <option <?php if($icon == 'fa-shopping-cart'){echo 'selected';}?> value='fa-shopping-cart'>&#xf07a; fa-shopping-cart</option>
        <option <?php if($icon == 'fa-shower'){echo 'selected';}?> value='fa-shower'>&#xf2cc; fa-shower</option>
        <option <?php if($icon == 'fa-sign-in'){echo 'selected';}?> value='fa-sign-in'>&#xf090; fa-sign-in</option>
        <option <?php if($icon == 'fa-sign-language'){echo 'selected';}?> value='fa-sign-language'>&#xf2a7; fa-sign-language</option>
        <option <?php if($icon == 'fa-sign-out'){echo 'selected';}?> value='fa-sign-out'>&#xf08b; fa-sign-out</option>
        <option <?php if($icon == 'fa-signal'){echo 'selected';}?> value='fa-signal'>&#xf012; fa-signal</option>
        <option <?php if($icon == 'fa-signing'){echo 'selected';}?> value='fa-signing'>&#xf2a7; fa-signing</option>
        <option <?php if($icon == 'fa-simplybuilt'){echo 'selected';}?> value='fa-simplybuilt'>&#xf215; fa-simplybuilt</option>
        <option <?php if($icon == 'fa-sitemap'){echo 'selected';}?> value='fa-sitemap'>&#xf0e8; fa-sitemap</option>
        <option <?php if($icon == 'fa-skyatlas'){echo 'selected';}?> value='fa-skyatlas'>&#xf216; fa-skyatlas</option>
        <option <?php if($icon == 'fa-skype'){echo 'selected';}?> value='fa-skype'>&#xf17e; fa-skype</option>
        <option <?php if($icon == 'fa-slack'){echo 'selected';}?> value='fa-slack'>&#xf198; fa-slack</option>
        <option <?php if($icon == 'fa-sliders'){echo 'selected';}?> value='fa-sliders'>&#xf1de; fa-sliders</option>
        <option <?php if($icon == 'fa-slideshare'){echo 'selected';}?> value='fa-slideshare'>&#xf1e7; fa-slideshare</option>
        <option <?php if($icon == 'fa-smile-o'){echo 'selected';}?> value='fa-smile-o'>&#xf118; fa-smile-o</option>
        <option <?php if($icon == 'fa-snapchat'){echo 'selected';}?> value='fa-snapchat'>&#xf2ab; fa-snapchat</option>
        <option <?php if($icon == 'fa-snapchat-ghost'){echo 'selected';}?> value='fa-snapchat-ghost'>&#xf2ac; fa-snapchat-ghost</option>
        <option <?php if($icon == 'fa-snapchat-square'){echo 'selected';}?> value='fa-snapchat-square'>&#xf2ad; fa-snapchat-square</option>
        <option <?php if($icon == 'fa-snowflake-o'){echo 'selected';}?> value='fa-snowflake-o'>&#xf2dc; fa-snowflake-o</option>
        <option <?php if($icon == 'fa-soccer-ball-o'){echo 'selected';}?> value='fa-soccer-ball-o'>&#xf1e3; fa-soccer-ball-o</option>
        <option <?php if($icon == 'fa-sort'){echo 'selected';}?> value='fa-sort'>&#xf0dc; fa-sort</option>
        <option <?php if($icon == 'fa-sort-alpha-asc'){echo 'selected';}?> value='fa-sort-alpha-asc'>&#xf15d; fa-sort-alpha-asc</option>
        <option <?php if($icon == 'fa-sort-alpha-desc'){echo 'selected';}?> value='fa-sort-alpha-desc'>&#xf15e; fa-sort-alpha-desc</option>
        <option <?php if($icon == 'fa-sort-amount-asc'){echo 'selected';}?> value='fa-sort-amount-asc'>&#xf160; fa-sort-amount-asc</option>
        <option <?php if($icon == 'fa-sort-amount-desc'){echo 'selected';}?> value='fa-sort-amount-desc'>&#xf161; fa-sort-amount-desc</option>
        <option <?php if($icon == 'fa-sort-asc'){echo 'selected';}?> value='fa-sort-asc'>&#xf0de; fa-sort-asc</option>
        <option <?php if($icon == 'fa-sort-desc'){echo 'selected';}?> value='fa-sort-desc'>&#xf0dd; fa-sort-desc</option>
        <option <?php if($icon == 'fa-sort-down'){echo 'selected';}?> value='fa-sort-down'>&#xf0dd; fa-sort-down</option>
        <option <?php if($icon == 'fa-sort-numeric-asc'){echo 'selected';}?> value='fa-sort-numeric-asc'>&#xf162; fa-sort-numeric-asc</option>
        <option <?php if($icon == 'fa-sort-numeric-desc'){echo 'selected';}?> value='fa-sort-numeric-desc'>&#xf163; fa-sort-numeric-desc</option>
        <option <?php if($icon == 'fa-sort-up'){echo 'selected';}?> value='fa-sort-up'>&#xf0de; fa-sort-up</option>
        <option <?php if($icon == 'fa-soundcloud'){echo 'selected';}?> value='fa-soundcloud'>&#xf1be; fa-soundcloud</option>
        <option <?php if($icon == 'fa-space-shuttle'){echo 'selected';}?> value='fa-space-shuttle'>&#xf197; fa-space-shuttle</option>
        <option <?php if($icon == 'fa-spinner'){echo 'selected';}?> value='fa-spinner'>&#xf110; fa-spinner</option>
        <option <?php if($icon == 'fa-spoon'){echo 'selected';}?> value='fa-spoon'>&#xf1b1; fa-spoon</option>
        <option <?php if($icon == 'fa-spotify'){echo 'selected';}?> value='fa-spotify'>&#xf1bc; fa-spotify</option>
        <option <?php if($icon == 'fa-square'){echo 'selected';}?> value='fa-square'>&#xf0c8; fa-square</option>
        <option <?php if($icon == 'fa-square-o'){echo 'selected';}?> value='fa-square-o'>&#xf096; fa-square-o</option>
        <option <?php if($icon == 'fa-stack-exchange'){echo 'selected';}?> value='fa-stack-exchange'>&#xf18d; fa-stack-exchange</option>
        <option <?php if($icon == 'fa-stack-overflow'){echo 'selected';}?> value='fa-stack-overflow'>&#xf16c; fa-stack-overflow</option>
        <option <?php if($icon == 'fa-star'){echo 'selected';}?> value='fa-star'>&#xf005; fa-star</option>
        <option <?php if($icon == 'fa-star-half'){echo 'selected';}?> value='fa-star-half'>&#xf089; fa-star-half</option>
        <option <?php if($icon == 'fa-star-half-empty'){echo 'selected';}?> value='fa-star-half-empty'>&#xf123; fa-star-half-empty</option>
        <option <?php if($icon == 'fa-star-half-full'){echo 'selected';}?> value='fa-star-half-full'>&#xf123; fa-star-half-full</option>
        <option <?php if($icon == 'fa-star-half-o'){echo 'selected';}?> value='fa-star-half-o'>&#xf123; fa-star-half-o</option>
        <option <?php if($icon == 'fa-star-o'){echo 'selected';}?> value='fa-star-o'>&#xf006; fa-star-o</option>
        <option <?php if($icon == 'fa-steam'){echo 'selected';}?> value='fa-steam'>&#xf1b6; fa-steam</option>
        <option <?php if($icon == 'fa-steam-square'){echo 'selected';}?> value='fa-steam-square'>&#xf1b7; fa-steam-square</option>
        <option <?php if($icon == 'fa-step-backward'){echo 'selected';}?> value='fa-step-backward'>&#xf048; fa-step-backward</option>
        <option <?php if($icon == 'fa-step-forward'){echo 'selected';}?> value='fa-step-forward'>&#xf051; fa-step-forward</option>
        <option <?php if($icon == 'fa-stethoscope'){echo 'selected';}?> value='fa-stethoscope'>&#xf0f1; fa-stethoscope</option>
        <option <?php if($icon == 'fa-sticky-note'){echo 'selected';}?> value='fa-sticky-note'>&#xf249; fa-sticky-note</option>
        <option <?php if($icon == 'fa-sticky-note-o'){echo 'selected';}?> value='fa-sticky-note-o'>&#xf24a; fa-sticky-note-o</option>
        <option <?php if($icon == 'fa-stop'){echo 'selected';}?> value='fa-stop'>&#xf04d; fa-stop</option>
        <option <?php if($icon == 'fa-stop-circle'){echo 'selected';}?> value='fa-stop-circle'>&#xf28d; fa-stop-circle</option>
        <option <?php if($icon == 'fa-stop-circle-o'){echo 'selected';}?> value='fa-stop-circle-o'>&#xf28e; fa-stop-circle-o</option>
        <option <?php if($icon == 'fa-street-view'){echo 'selected';}?> value='fa-street-view'>&#xf21d; fa-street-view</option>
        <option <?php if($icon == 'fa-strikethrough'){echo 'selected';}?> value='fa-strikethrough'>&#xf0cc; fa-strikethrough</option>
        <option <?php if($icon == 'fa-stumbleupon'){echo 'selected';}?> value='fa-stumbleupon'>&#xf1a4; fa-stumbleupon</option>
        <option <?php if($icon == 'fa-stumbleupon-circle'){echo 'selected';}?> value='fa-stumbleupon-circle'>&#xf1a3; fa-stumbleupon-circle</option>
        <option <?php if($icon == 'fa-subscript'){echo 'selected';}?> value='fa-subscript'>&#xf12c; fa-subscript</option>
        <option <?php if($icon == 'fa-subway'){echo 'selected';}?> value='fa-subway'>&#xf239; fa-subway</option>
        <option <?php if($icon == 'fa-suitcase'){echo 'selected';}?> value='fa-suitcase'>&#xf0f2; fa-suitcase</option>
        <option <?php if($icon == 'fa-sun-o'){echo 'selected';}?> value='fa-sun-o'>&#xf185; fa-sun-o</option>
        <option <?php if($icon == 'fa-superpowers'){echo 'selected';}?> value='fa-superpowers'>&#xf2dd; fa-superpowers</option>
        <option <?php if($icon == 'fa-superscript'){echo 'selected';}?> value='fa-superscript'>&#xf12b; fa-superscript</option>
        <option <?php if($icon == 'fa-support'){echo 'selected';}?> value='fa-support'>&#xf1cd; fa-support</option>
        <option <?php if($icon == 'fa-table'){echo 'selected';}?> value='fa-table'>&#xf0ce; fa-table</option>
        <option <?php if($icon == 'fa-tablet'){echo 'selected';}?> value='fa-tablet'>&#xf10a; fa-tablet</option>
        <option <?php if($icon == 'fa-tachometer'){echo 'selected';}?> value='fa-tachometer'>&#xf0e4; fa-tachometer</option>
        <option <?php if($icon == 'fa-tag'){echo 'selected';}?> value='fa-tag'>&#xf02b; fa-tag</option>
        <option <?php if($icon == 'fa-tags'){echo 'selected';}?> value='fa-tags'>&#xf02c; fa-tags</option>
        <option <?php if($icon == 'fa-tasks'){echo 'selected';}?> value='fa-tasks'>&#xf0ae; fa-tasks</option>
        <option <?php if($icon == 'fa-taxi'){echo 'selected';}?> value='fa-taxi'>&#xf1ba; fa-taxi</option>
        <option <?php if($icon == 'fa-telegram'){echo 'selected';}?> value='fa-telegram'>&#xf2c6; fa-telegram</option>
        <option <?php if($icon == 'fa-television'){echo 'selected';}?> value='fa-television'>&#xf26c; fa-television</option>
        <option <?php if($icon == 'fa-tencent-weibo'){echo 'selected';}?> value='fa-tencent-weibo'>&#xf1d5; fa-tencent-weibo</option>
        <option <?php if($icon == 'fa-terminal'){echo 'selected';}?> value='fa-terminal'>&#xf120; fa-terminal</option>
        <option <?php if($icon == 'fa-text-height'){echo 'selected';}?> value='fa-text-height'>&#xf034; fa-text-height</option>
        <option <?php if($icon == 'fa-text-width'){echo 'selected';}?> value='fa-text-width'>&#xf035; fa-text-width</option>
        <option <?php if($icon == 'fa-th'){echo 'selected';}?> value='fa-th'>&#xf00a; fa-th</option>
        <option <?php if($icon == 'fa-th-large'){echo 'selected';}?> value='fa-th-large'>&#xf009; fa-th-large</option>
        <option <?php if($icon == 'fa-th-list'){echo 'selected';}?> value='fa-th-list'>&#xf00b; fa-th-list</option>
        <option <?php if($icon == 'fa-themeisle'){echo 'selected';}?> value='fa-themeisle'>&#xf2b2; fa-themeisle</option>
        <option <?php if($icon == 'fa-thermometer'){echo 'selected';}?> value='fa-thermometer'>&#xf2c7; fa-thermometer</option>
        <option <?php if($icon == 'fa-thermometer-0'){echo 'selected';}?> value='fa-thermometer-0'>&#xf2cb; fa-thermometer-0</option>
        <option <?php if($icon == 'fa-thermometer-1'){echo 'selected';}?> value='fa-thermometer-1'>&#xf2ca; fa-thermometer-1</option>
        <option <?php if($icon == 'fa-thermometer-2'){echo 'selected';}?> value='fa-thermometer-2'>&#xf2c9; fa-thermometer-2</option>
        <option <?php if($icon == 'fa-thermometer-3'){echo 'selected';}?> value='fa-thermometer-3'>&#xf2c8; fa-thermometer-3</option>
        <option <?php if($icon == 'fa-thermometer-4'){echo 'selected';}?> value='fa-thermometer-4'>&#xf2c7; fa-thermometer-4</option>
        <option <?php if($icon == 'fa-thermometer-empty'){echo 'selected';}?> value='fa-thermometer-empty'>&#xf2cb; fa-thermometer-empty</option>
        <option <?php if($icon == 'fa-thermometer-full'){echo 'selected';}?> value='fa-thermometer-full'>&#xf2c7; fa-thermometer-full</option>
        <option <?php if($icon == 'fa-thermometer-half'){echo 'selected';}?> value='fa-thermometer-half'>&#xf2c9; fa-thermometer-half</option>
        <option <?php if($icon == 'fa-thermometer-quarter'){echo 'selected';}?> value='fa-thermometer-quarter'>&#xf2ca; fa-thermometer-quarter</option>
        <option <?php if($icon == 'fa-thermometer-three-quarters'){echo 'selected';}?> value='fa-thermometer-three-quarters'>&#xf2c8; fa-thermometer-three-quarters</option>
        <option <?php if($icon == 'fa-thumb-tack'){echo 'selected';}?> value='fa-thumb-tack'>&#xf08d; fa-thumb-tack</option>
        <option <?php if($icon == 'fa-thumbs-down'){echo 'selected';}?> value='fa-thumbs-down'>&#xf165; fa-thumbs-down</option>
        <option <?php if($icon == 'fa-thumbs-o-down'){echo 'selected';}?> value='fa-thumbs-o-down'>&#xf088; fa-thumbs-o-down</option>
        <option <?php if($icon == 'fa-thumbs-o-up'){echo 'selected';}?> value='fa-thumbs-o-up'>&#xf087; fa-thumbs-o-up</option>
        <option <?php if($icon == 'fa-thumbs-up'){echo 'selected';}?> value='fa-thumbs-up'>&#xf164; fa-thumbs-up</option>
        <option <?php if($icon == 'fa-ticket'){echo 'selected';}?> value='fa-ticket'>&#xf145; fa-ticket</option>
        <option <?php if($icon == 'fa-times'){echo 'selected';}?> value='fa-times'>&#xf00d; fa-times</option>
        <option <?php if($icon == 'fa-times-circle'){echo 'selected';}?> value='fa-times-circle'>&#xf057; fa-times-circle</option>
        <option <?php if($icon == 'fa-times-circle-o'){echo 'selected';}?> value='fa-times-circle-o'>&#xf05c; fa-times-circle-o</option>
        <option <?php if($icon == 'fa-times-rectangle'){echo 'selected';}?> value='fa-times-rectangle'>&#xf2d3; fa-times-rectangle</option>
        <option <?php if($icon == 'fa-times-rectangle-o'){echo 'selected';}?> value='fa-times-rectangle-o'>&#xf2d4; fa-times-rectangle-o</option>
        <option <?php if($icon == 'fa-tint'){echo 'selected';}?> value='fa-tint'>&#xf043; fa-tint</option>
        <option <?php if($icon == 'fa-toggle-down'){echo 'selected';}?> value='fa-toggle-down'>&#xf150; fa-toggle-down</option>
        <option <?php if($icon == 'fa-toggle-left'){echo 'selected';}?> value='fa-toggle-left'>&#xf191; fa-toggle-left</option>
        <option <?php if($icon == 'fa-toggle-off'){echo 'selected';}?> value='fa-toggle-off'>&#xf204; fa-toggle-off</option>
        <option <?php if($icon == 'fa-toggle-on'){echo 'selected';}?> value='fa-toggle-on'>&#xf205; fa-toggle-on</option>
        <option <?php if($icon == 'fa-toggle-right'){echo 'selected';}?> value='fa-toggle-right'>&#xf152; fa-toggle-right</option>
        <option <?php if($icon == 'fa-toggle-up'){echo 'selected';}?> value='fa-toggle-up'>&#xf151; fa-toggle-up</option>
        <option <?php if($icon == 'fa-trademark'){echo 'selected';}?> value='fa-trademark'>&#xf25c; fa-trademark</option>
        <option <?php if($icon == 'fa-train'){echo 'selected';}?> value='fa-train'>&#xf238; fa-train</option>
        <option <?php if($icon == 'fa-transgender'){echo 'selected';}?> value='fa-transgender'>&#xf224; fa-transgender</option>
        <option <?php if($icon == 'fa-transgender-alt'){echo 'selected';}?> value='fa-transgender-alt'>&#xf225; fa-transgender-alt</option>
        <option <?php if($icon == 'fa-trash'){echo 'selected';}?> value='fa-trash'>&#xf1f8; fa-trash</option>
        <option <?php if($icon == 'fa-trash-o'){echo 'selected';}?> value='fa-trash-o'>&#xf014; fa-trash-o</option>
        <option <?php if($icon == 'fa-tree'){echo 'selected';}?> value='fa-tree'>&#xf1bb; fa-tree</option>
        <option <?php if($icon == 'fa-trello'){echo 'selected';}?> value='fa-trello'>&#xf181; fa-trello</option>
        <option <?php if($icon == 'fa-tripadvisor'){echo 'selected';}?> value='fa-tripadvisor'>&#xf262; fa-tripadvisor</option>
        <option <?php if($icon == 'fa-trophy'){echo 'selected';}?> value='fa-trophy'>&#xf091; fa-trophy</option>
        <option <?php if($icon == 'fa-truck'){echo 'selected';}?> value='fa-truck'>&#xf0d1; fa-truck</option>
        <option <?php if($icon == 'fa-try'){echo 'selected';}?> value='fa-try'>&#xf195; fa-try</option>
        <option <?php if($icon == 'fa-tty'){echo 'selected';}?> value='fa-tty'>&#xf1e4; fa-tty</option>
        <option <?php if($icon == 'fa-tumblr'){echo 'selected';}?> value='fa-tumblr'>&#xf173; fa-tumblr</option>
        <option <?php if($icon == 'fa-tumblr-square'){echo 'selected';}?> value='fa-tumblr-square'>&#xf174; fa-tumblr-square</option>
        <option <?php if($icon == 'fa-turkish-lira'){echo 'selected';}?> value='fa-turkish-lira'>&#xf195; fa-turkish-lira</option>
        <option <?php if($icon == 'fa-tv'){echo 'selected';}?> value='fa-tv'>&#xf26c; fa-tv</option>
        <option <?php if($icon == 'fa-twitch'){echo 'selected';}?> value='fa-twitch'>&#xf1e8; fa-twitch</option>
        <option <?php if($icon == 'fa-twitter'){echo 'selected';}?> value='fa-twitter'>&#xf099; fa-twitter</option>
        <option <?php if($icon == 'fa-twitter-square'){echo 'selected';}?> value='fa-twitter-square'>&#xf081; fa-twitter-square</option>
        <option <?php if($icon == 'fa-umbrella'){echo 'selected';}?> value='fa-umbrella'>&#xf0e9; fa-umbrella</option>
        <option <?php if($icon == 'fa-underline'){echo 'selected';}?> value='fa-underline'>&#xf0cd; fa-underline</option>
        <option <?php if($icon == 'fa-undo'){echo 'selected';}?> value='fa-undo'>&#xf0e2; fa-undo</option>
        <option <?php if($icon == 'fa-universal-access'){echo 'selected';}?> value='fa-universal-access'>&#xf29a; fa-universal-access</option>
        <option <?php if($icon == 'fa-university'){echo 'selected';}?> value='fa-university'>&#xf19c; fa-university</option>
        <option <?php if($icon == 'fa-unlink'){echo 'selected';}?> value='fa-unlink'>&#xf127; fa-unlink</option>
        <option <?php if($icon == 'fa-unlock'){echo 'selected';}?> value='fa-unlock'>&#xf09c; fa-unlock</option>
        <option <?php if($icon == 'fa-unlock-alt'){echo 'selected';}?> value='fa-unlock-alt'>&#xf13e; fa-unlock-alt</option>
        <option <?php if($icon == 'fa-unsorted'){echo 'selected';}?> value='fa-unsorted'>&#xf0dc; fa-unsorted</option>
        <option <?php if($icon == 'fa-upload'){echo 'selected';}?> value='fa-upload'>&#xf093; fa-upload</option>
        <option <?php if($icon == 'fa-usb'){echo 'selected';}?> value='fa-usb'>&#xf287; fa-usb</option>
        <option <?php if($icon == 'fa-usd'){echo 'selected';}?> value='fa-usd'>&#xf155; fa-usd</option>
        <option <?php if($icon == 'fa-user'){echo 'selected';}?> value='fa-user'>&#xf007; fa-user</option>
        <option <?php if($icon == 'fa-user-circle'){echo 'selected';}?> value='fa-user-circle'>&#xf2bd; fa-user-circle</option>
        <option <?php if($icon == 'fa-user-circle-o'){echo 'selected';}?> value='fa-user-circle-o'>&#xf2be; fa-user-circle-o</option>
        <option <?php if($icon == 'fa-user-md'){echo 'selected';}?> value='fa-user-md'>&#xf0f0; fa-user-md</option>
        <option <?php if($icon == 'fa-user-o'){echo 'selected';}?> value='fa-user-o'>&#xf2c0; fa-user-o</option>
        <option <?php if($icon == 'fa-user-plus'){echo 'selected';}?> value='fa-user-plus'>&#xf234; fa-user-plus</option>
        <option <?php if($icon == 'fa-user-secret'){echo 'selected';}?> value='fa-user-secret'>&#xf21b; fa-user-secret</option>
        <option <?php if($icon == 'fa-user-times'){echo 'selected';}?> value='fa-user-times'>&#xf235; fa-user-times</option>
        <option <?php if($icon == 'fa-users'){echo 'selected';}?> value='fa-users'>&#xf0c0; fa-users</option>
        <option <?php if($icon == 'fa-vcard'){echo 'selected';}?> value='fa-vcard'>&#xf2bb; fa-vcard</option>
        <option <?php if($icon == 'fa-vcard-o'){echo 'selected';}?> value='fa-vcard-o'>&#xf2bc; fa-vcard-o</option>
        <option <?php if($icon == 'fa-venus'){echo 'selected';}?> value='fa-venus'>&#xf221; fa-venus</option>
        <option <?php if($icon == 'fa-venus-double'){echo 'selected';}?> value='fa-venus-double'>&#xf226; fa-venus-double</option>
        <option <?php if($icon == 'fa-venus-mars'){echo 'selected';}?> value='fa-venus-mars'>&#xf228; fa-venus-mars</option>
        <option <?php if($icon == 'fa-viacoin'){echo 'selected';}?> value='fa-viacoin'>&#xf237; fa-viacoin</option>
        <option <?php if($icon == 'fa-viadeo'){echo 'selected';}?> value='fa-viadeo'>&#xf2a9; fa-viadeo</option>
        <option <?php if($icon == 'fa-viadeo-square'){echo 'selected';}?> value='fa-viadeo-square'>&#xf2aa; fa-viadeo-square</option>
        <option <?php if($icon == 'fa-video-camera'){echo 'selected';}?> value='fa-video-camera'>&#xf03d; fa-video-camera</option>
        <option <?php if($icon == 'fa-vimeo'){echo 'selected';}?> value='fa-vimeo'>&#xf27d; fa-vimeo</option>
        <option <?php if($icon == 'fa-vimeo-square'){echo 'selected';}?> value='fa-vimeo-square'>&#xf194; fa-vimeo-square</option>
        <option <?php if($icon == 'fa-vine'){echo 'selected';}?> value='fa-vine'>&#xf1ca; fa-vine</option>
        <option <?php if($icon == 'fa-vk'){echo 'selected';}?> value='fa-vk'>&#xf189; fa-vk</option>
        <option <?php if($icon == 'fa-volume-control-phone'){echo 'selected';}?> value='fa-volume-control-phone'>&#xf2a0; fa-volume-control-phone</option>
        <option <?php if($icon == 'fa-volume-down'){echo 'selected';}?> value='fa-volume-down'>&#xf027; fa-volume-down</option>
        <option <?php if($icon == 'fa-volume-off'){echo 'selected';}?> value='fa-volume-off'>&#xf026; fa-volume-off</option>
        <option <?php if($icon == 'fa-volume-up'){echo 'selected';}?> value='fa-volume-up'>&#xf028; fa-volume-up</option>
        <option <?php if($icon == 'fa-warning'){echo 'selected';}?> value='fa-warning'>&#xf071; fa-warning</option>
        <option <?php if($icon == 'fa-wechat'){echo 'selected';}?> value='fa-wechat'>&#xf1d7; fa-wechat</option>
        <option <?php if($icon == 'fa-weibo'){echo 'selected';}?> value='fa-weibo'>&#xf18a; fa-weibo</option>
        <option <?php if($icon == 'fa-weixin'){echo 'selected';}?> value='fa-weixin'>&#xf1d7; fa-weixin</option>
        <option <?php if($icon == 'fa-whatsapp'){echo 'selected';}?> value='fa-whatsapp'>&#xf232; fa-whatsapp</option>
        <option <?php if($icon == 'fa-wheelchair'){echo 'selected';}?> value='fa-wheelchair'>&#xf193; fa-wheelchair</option>
        <option <?php if($icon == 'fa-wheelchair-alt'){echo 'selected';}?> value='fa-wheelchair-alt'>&#xf29b; fa-wheelchair-alt</option>
        <option <?php if($icon == 'fa-wifi'){echo 'selected';}?> value='fa-wifi'>&#xf1eb; fa-wifi</option>
        <option <?php if($icon == 'fa-wikipedia-w'){echo 'selected';}?> value='fa-wikipedia-w'>&#xf266; fa-wikipedia-w</option>
        <option <?php if($icon == 'fa-window-close'){echo 'selected';}?> value='fa-window-close'>&#xf2d3; fa-window-close</option>
        <option <?php if($icon == 'fa-window-close-o'){echo 'selected';}?> value='fa-window-close-o'>&#xf2d4; fa-window-close-o</option>
        <option <?php if($icon == 'fa-window-maximize'){echo 'selected';}?> value='fa-window-maximize'>&#xf2d0; fa-window-maximize</option>
        <option <?php if($icon == 'fa-window-minimize'){echo 'selected';}?> value='fa-window-minimize'>&#xf2d1; fa-window-minimize</option>
        <option <?php if($icon == 'fa-window-restore'){echo 'selected';}?> value='fa-window-restore'>&#xf2d2; fa-window-restore</option>
        <option <?php if($icon == 'fa-windows'){echo 'selected';}?> value='fa-windows'>&#xf17a; fa-windows</option>
        <option <?php if($icon == 'fa-won'){echo 'selected';}?> value='fa-won'>&#xf159; fa-won</option>
        <option <?php if($icon == 'fa-wordpress'){echo 'selected';}?> value='fa-wordpress'>&#xf19a; fa-wordpress</option>
        <option <?php if($icon == 'fa-wpbeginner'){echo 'selected';}?> value='fa-wpbeginner'>&#xf297; fa-wpbeginner</option>
        <option <?php if($icon == 'fa-wpexplorer'){echo 'selected';}?> value='fa-wpexplorer'>&#xf2de; fa-wpexplorer</option>
        <option <?php if($icon == 'fa-wpforms'){echo 'selected';}?> value='fa-wpforms'>&#xf298; fa-wpforms</option>
        <option <?php if($icon == 'fa-wrench'){echo 'selected';}?> value='fa-wrench'>&#xf0ad; fa-wrench</option>
        <option <?php if($icon == 'fa-xing'){echo 'selected';}?> value='fa-xing'>&#xf168; fa-xing</option>
        <option <?php if($icon == 'fa-xing-square'){echo 'selected';}?> value='fa-xing-square'>&#xf169; fa-xing-square</option>
        <option <?php if($icon == 'fa-y-combinator'){echo 'selected';}?> value='fa-y-combinator'>&#xf23b; fa-y-combinator</option>
        <option <?php if($icon == 'fa-y-combinator-square'){echo 'selected';}?> value='fa-y-combinator-square'>&#xf1d4; fa-y-combinator-square</option>
        <option <?php if($icon == 'fa-yahoo'){echo 'selected';}?> value='fa-yahoo'>&#xf19e; fa-yahoo</option>
        <option <?php if($icon == 'fa-yc'){echo 'selected';}?> value='fa-yc'>&#xf23b; fa-yc</option>
        <option <?php if($icon == 'fa-yc-square'){echo 'selected';}?> value='fa-yc-square'>&#xf1d4; fa-yc-square</option>
        <option <?php if($icon == 'fa-yelp'){echo 'selected';}?> value='fa-yelp'>&#xf1e9; fa-yelp</option>
        